// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/category"
	"go-wind-admin/app/admin/service/internal/data/ent/categorydefaultfeature"
	"go-wind-admin/app/admin/service/internal/data/ent/feature"
	"go-wind-admin/app/admin/service/internal/data/ent/schema"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 分类默认模型条目（CR-001：承载完整 spec）/ Category default model entry (full spec)
type CategoryDefaultFeature struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 是否启用
	IsEnabled *bool `json:"is_enabled,omitempty"`
	// 排序值（越小越靠前）
	SortOrder *uint32 `json:"sort_order,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 分类 ID（必须 level=4）/ Category id, must be level=4
	CategoryID uint32 `json:"category_id,omitempty"`
	// 全局特征 ID（骨架来源）/ Global feature id (skeleton source)
	FeatureID uint32 `json:"feature_id,omitempty"`
	// 完整 FeatureSpec（按 feature_type 解读，protojson）/ Full feature spec (protojson)
	Spec *schema.FeatureSpecField `json:"spec,omitempty"`
	// 分类内展示别名 / Display alias within category
	DisplayName *string `json:"display_name,omitempty"`
	// property 数据类型（从 spec 派生）/ Property data type
	DataType *categorydefaultfeature.DataType `json:"data_type,omitempty"`
	// property 访问模式 R/RW / Property access mode
	AccessMode *categorydefaultfeature.AccessMode `json:"access_mode,omitempty"`
	// event 级别 / Event level
	EventLevel *categorydefaultfeature.EventLevel `json:"event_level,omitempty"`
	// service 调用模式 / Service call mode
	CallMode *categorydefaultfeature.CallMode `json:"call_mode,omitempty"`
	// relation 关系类型 / Relation type
	RelationType *string `json:"relation_type,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CategoryDefaultFeatureQuery when eager-loading is set.
	Edges        CategoryDefaultFeatureEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CategoryDefaultFeatureEdges holds the relations/edges for other nodes in the graph.
type CategoryDefaultFeatureEdges struct {
	// Category holds the value of the category edge.
	Category *Category `json:"category,omitempty"`
	// Feature holds the value of the feature edge.
	Feature *Feature `json:"feature,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CategoryDefaultFeatureEdges) CategoryOrErr() (*Category, error) {
	if e.Category != nil {
		return e.Category, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: category.Label}
	}
	return nil, &NotLoadedError{edge: "category"}
}

// FeatureOrErr returns the Feature value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CategoryDefaultFeatureEdges) FeatureOrErr() (*Feature, error) {
	if e.Feature != nil {
		return e.Feature, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: feature.Label}
	}
	return nil, &NotLoadedError{edge: "feature"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CategoryDefaultFeature) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case categorydefaultfeature.FieldSpec:
			values[i] = new([]byte)
		case categorydefaultfeature.FieldIsEnabled:
			values[i] = new(sql.NullBool)
		case categorydefaultfeature.FieldID, categorydefaultfeature.FieldCreatedBy, categorydefaultfeature.FieldUpdatedBy, categorydefaultfeature.FieldDeletedBy, categorydefaultfeature.FieldSortOrder, categorydefaultfeature.FieldTenantID, categorydefaultfeature.FieldCategoryID, categorydefaultfeature.FieldFeatureID:
			values[i] = new(sql.NullInt64)
		case categorydefaultfeature.FieldDisplayName, categorydefaultfeature.FieldDataType, categorydefaultfeature.FieldAccessMode, categorydefaultfeature.FieldEventLevel, categorydefaultfeature.FieldCallMode, categorydefaultfeature.FieldRelationType:
			values[i] = new(sql.NullString)
		case categorydefaultfeature.FieldCreatedAt, categorydefaultfeature.FieldUpdatedAt, categorydefaultfeature.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CategoryDefaultFeature fields.
func (_m *CategoryDefaultFeature) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case categorydefaultfeature.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case categorydefaultfeature.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case categorydefaultfeature.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case categorydefaultfeature.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case categorydefaultfeature.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case categorydefaultfeature.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case categorydefaultfeature.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case categorydefaultfeature.FieldIsEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_enabled", values[i])
			} else if value.Valid {
				_m.IsEnabled = new(bool)
				*_m.IsEnabled = value.Bool
			}
		case categorydefaultfeature.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = new(uint32)
				*_m.SortOrder = uint32(value.Int64)
			}
		case categorydefaultfeature.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case categorydefaultfeature.FieldCategoryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field category_id", values[i])
			} else if value.Valid {
				_m.CategoryID = uint32(value.Int64)
			}
		case categorydefaultfeature.FieldFeatureID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field feature_id", values[i])
			} else if value.Valid {
				_m.FeatureID = uint32(value.Int64)
			}
		case categorydefaultfeature.FieldSpec:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field spec", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Spec); err != nil {
					return fmt.Errorf("unmarshal field spec: %w", err)
				}
			}
		case categorydefaultfeature.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = new(string)
				*_m.DisplayName = value.String
			}
		case categorydefaultfeature.FieldDataType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field data_type", values[i])
			} else if value.Valid {
				_m.DataType = new(categorydefaultfeature.DataType)
				*_m.DataType = categorydefaultfeature.DataType(value.String)
			}
		case categorydefaultfeature.FieldAccessMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_mode", values[i])
			} else if value.Valid {
				_m.AccessMode = new(categorydefaultfeature.AccessMode)
				*_m.AccessMode = categorydefaultfeature.AccessMode(value.String)
			}
		case categorydefaultfeature.FieldEventLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_level", values[i])
			} else if value.Valid {
				_m.EventLevel = new(categorydefaultfeature.EventLevel)
				*_m.EventLevel = categorydefaultfeature.EventLevel(value.String)
			}
		case categorydefaultfeature.FieldCallMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field call_mode", values[i])
			} else if value.Valid {
				_m.CallMode = new(categorydefaultfeature.CallMode)
				*_m.CallMode = categorydefaultfeature.CallMode(value.String)
			}
		case categorydefaultfeature.FieldRelationType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field relation_type", values[i])
			} else if value.Valid {
				_m.RelationType = new(string)
				*_m.RelationType = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CategoryDefaultFeature.
// This includes values selected through modifiers, order, etc.
func (_m *CategoryDefaultFeature) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCategory queries the "category" edge of the CategoryDefaultFeature entity.
func (_m *CategoryDefaultFeature) QueryCategory() *CategoryQuery {
	return NewCategoryDefaultFeatureClient(_m.config).QueryCategory(_m)
}

// QueryFeature queries the "feature" edge of the CategoryDefaultFeature entity.
func (_m *CategoryDefaultFeature) QueryFeature() *FeatureQuery {
	return NewCategoryDefaultFeatureClient(_m.config).QueryFeature(_m)
}

// Update returns a builder for updating this CategoryDefaultFeature.
// Note that you need to call CategoryDefaultFeature.Unwrap() before calling this method if this CategoryDefaultFeature
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CategoryDefaultFeature) Update() *CategoryDefaultFeatureUpdateOne {
	return NewCategoryDefaultFeatureClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CategoryDefaultFeature entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CategoryDefaultFeature) Unwrap() *CategoryDefaultFeature {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CategoryDefaultFeature is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CategoryDefaultFeature) String() string {
	var builder strings.Builder
	builder.WriteString("CategoryDefaultFeature(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.IsEnabled; v != nil {
		builder.WriteString("is_enabled=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SortOrder; v != nil {
		builder.WriteString("sort_order=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("category_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CategoryID))
	builder.WriteString(", ")
	builder.WriteString("feature_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeatureID))
	builder.WriteString(", ")
	builder.WriteString("spec=")
	builder.WriteString(fmt.Sprintf("%v", _m.Spec))
	builder.WriteString(", ")
	if v := _m.DisplayName; v != nil {
		builder.WriteString("display_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DataType; v != nil {
		builder.WriteString("data_type=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AccessMode; v != nil {
		builder.WriteString("access_mode=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.EventLevel; v != nil {
		builder.WriteString("event_level=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CallMode; v != nil {
		builder.WriteString("call_mode=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RelationType; v != nil {
		builder.WriteString("relation_type=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// CategoryDefaultFeatures is a parsable slice of CategoryDefaultFeature.
type CategoryDefaultFeatures []*CategoryDefaultFeature
