// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-wind-admin/app/admin/service/internal/data/ent/categorydefaultfeature"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CategoryDefaultFeatureDelete is the builder for deleting a CategoryDefaultFeature entity.
type CategoryDefaultFeatureDelete struct {
	config
	hooks    []Hook
	mutation *CategoryDefaultFeatureMutation
}

// Where appends a list predicates to the CategoryDefaultFeatureDelete builder.
func (_d *CategoryDefaultFeatureDelete) Where(ps ...predicate.CategoryDefaultFeature) *CategoryDefaultFeatureDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CategoryDefaultFeatureDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CategoryDefaultFeatureDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CategoryDefaultFeatureDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(categorydefaultfeature.Table, sqlgraph.NewFieldSpec(categorydefaultfeature.FieldID, field.TypeUint32))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CategoryDefaultFeatureDeleteOne is the builder for deleting a single CategoryDefaultFeature entity.
type CategoryDefaultFeatureDeleteOne struct {
	_d *CategoryDefaultFeatureDelete
}

// Where appends a list predicates to the CategoryDefaultFeatureDelete builder.
func (_d *CategoryDefaultFeatureDeleteOne) Where(ps ...predicate.CategoryDefaultFeature) *CategoryDefaultFeatureDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CategoryDefaultFeatureDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{categorydefaultfeature.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CategoryDefaultFeatureDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
