// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/categorydefaultfeature"
	"go-wind-admin/app/admin/service/internal/data/ent/feature"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FeatureUpdate is the builder for updating Feature entities.
type FeatureUpdate struct {
	config
	hooks     []Hook
	mutation  *FeatureMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the FeatureUpdate builder.
func (_u *FeatureUpdate) Where(ps ...predicate.Feature) *FeatureUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FeatureUpdate) SetUpdatedAt(v time.Time) *FeatureUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableUpdatedAt(v *time.Time) *FeatureUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *FeatureUpdate) ClearUpdatedAt() *FeatureUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FeatureUpdate) SetDeletedAt(v time.Time) *FeatureUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableDeletedAt(v *time.Time) *FeatureUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FeatureUpdate) ClearDeletedAt() *FeatureUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *FeatureUpdate) SetCreatedBy(v uint32) *FeatureUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableCreatedBy(v *uint32) *FeatureUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *FeatureUpdate) AddCreatedBy(v int32) *FeatureUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *FeatureUpdate) ClearCreatedBy() *FeatureUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *FeatureUpdate) SetUpdatedBy(v uint32) *FeatureUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableUpdatedBy(v *uint32) *FeatureUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *FeatureUpdate) AddUpdatedBy(v int32) *FeatureUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *FeatureUpdate) ClearUpdatedBy() *FeatureUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *FeatureUpdate) SetDeletedBy(v uint32) *FeatureUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableDeletedBy(v *uint32) *FeatureUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *FeatureUpdate) AddDeletedBy(v int32) *FeatureUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *FeatureUpdate) ClearDeletedBy() *FeatureUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *FeatureUpdate) SetIsEnabled(v bool) *FeatureUpdate {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableIsEnabled(v *bool) *FeatureUpdate {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (_u *FeatureUpdate) ClearIsEnabled() *FeatureUpdate {
	_u.mutation.ClearIsEnabled()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *FeatureUpdate) SetSortOrder(v uint32) *FeatureUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableSortOrder(v *uint32) *FeatureUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *FeatureUpdate) AddSortOrder(v int32) *FeatureUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (_u *FeatureUpdate) ClearSortOrder() *FeatureUpdate {
	_u.mutation.ClearSortOrder()
	return _u
}

// SetFeatureType sets the "feature_type" field.
func (_u *FeatureUpdate) SetFeatureType(v feature.FeatureType) *FeatureUpdate {
	_u.mutation.SetFeatureType(v)
	return _u
}

// SetNillableFeatureType sets the "feature_type" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableFeatureType(v *feature.FeatureType) *FeatureUpdate {
	if v != nil {
		_u.SetFeatureType(*v)
	}
	return _u
}

// ClearFeatureType clears the value of the "feature_type" field.
func (_u *FeatureUpdate) ClearFeatureType() *FeatureUpdate {
	_u.mutation.ClearFeatureType()
	return _u
}

// SetIdentifier sets the "identifier" field.
func (_u *FeatureUpdate) SetIdentifier(v string) *FeatureUpdate {
	_u.mutation.SetIdentifier(v)
	return _u
}

// SetNillableIdentifier sets the "identifier" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableIdentifier(v *string) *FeatureUpdate {
	if v != nil {
		_u.SetIdentifier(*v)
	}
	return _u
}

// ClearIdentifier clears the value of the "identifier" field.
func (_u *FeatureUpdate) ClearIdentifier() *FeatureUpdate {
	_u.mutation.ClearIdentifier()
	return _u
}

// SetName sets the "name" field.
func (_u *FeatureUpdate) SetName(v string) *FeatureUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableName(v *string) *FeatureUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *FeatureUpdate) ClearName() *FeatureUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetNameEn sets the "name_en" field.
func (_u *FeatureUpdate) SetNameEn(v string) *FeatureUpdate {
	_u.mutation.SetNameEn(v)
	return _u
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableNameEn(v *string) *FeatureUpdate {
	if v != nil {
		_u.SetNameEn(*v)
	}
	return _u
}

// ClearNameEn clears the value of the "name_en" field.
func (_u *FeatureUpdate) ClearNameEn() *FeatureUpdate {
	_u.mutation.ClearNameEn()
	return _u
}

// SetDescription sets the "description" field.
func (_u *FeatureUpdate) SetDescription(v string) *FeatureUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableDescription(v *string) *FeatureUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FeatureUpdate) ClearDescription() *FeatureUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetApplicableScope sets the "applicable_scope" field.
func (_u *FeatureUpdate) SetApplicableScope(v string) *FeatureUpdate {
	_u.mutation.SetApplicableScope(v)
	return _u
}

// SetNillableApplicableScope sets the "applicable_scope" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableApplicableScope(v *string) *FeatureUpdate {
	if v != nil {
		_u.SetApplicableScope(*v)
	}
	return _u
}

// ClearApplicableScope clears the value of the "applicable_scope" field.
func (_u *FeatureUpdate) ClearApplicableScope() *FeatureUpdate {
	_u.mutation.ClearApplicableScope()
	return _u
}

// SetRecommendedUnitCategoryID sets the "recommended_unit_category_id" field.
func (_u *FeatureUpdate) SetRecommendedUnitCategoryID(v uint32) *FeatureUpdate {
	_u.mutation.ResetRecommendedUnitCategoryID()
	_u.mutation.SetRecommendedUnitCategoryID(v)
	return _u
}

// SetNillableRecommendedUnitCategoryID sets the "recommended_unit_category_id" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableRecommendedUnitCategoryID(v *uint32) *FeatureUpdate {
	if v != nil {
		_u.SetRecommendedUnitCategoryID(*v)
	}
	return _u
}

// AddRecommendedUnitCategoryID adds value to the "recommended_unit_category_id" field.
func (_u *FeatureUpdate) AddRecommendedUnitCategoryID(v int32) *FeatureUpdate {
	_u.mutation.AddRecommendedUnitCategoryID(v)
	return _u
}

// ClearRecommendedUnitCategoryID clears the value of the "recommended_unit_category_id" field.
func (_u *FeatureUpdate) ClearRecommendedUnitCategoryID() *FeatureUpdate {
	_u.mutation.ClearRecommendedUnitCategoryID()
	return _u
}

// SetSemanticTag sets the "semantic_tag" field.
func (_u *FeatureUpdate) SetSemanticTag(v string) *FeatureUpdate {
	_u.mutation.SetSemanticTag(v)
	return _u
}

// SetNillableSemanticTag sets the "semantic_tag" field if the given value is not nil.
func (_u *FeatureUpdate) SetNillableSemanticTag(v *string) *FeatureUpdate {
	if v != nil {
		_u.SetSemanticTag(*v)
	}
	return _u
}

// ClearSemanticTag clears the value of the "semantic_tag" field.
func (_u *FeatureUpdate) ClearSemanticTag() *FeatureUpdate {
	_u.mutation.ClearSemanticTag()
	return _u
}

// AddCategoryDefaultEntryIDs adds the "category_default_entries" edge to the CategoryDefaultFeature entity by IDs.
func (_u *FeatureUpdate) AddCategoryDefaultEntryIDs(ids ...uint32) *FeatureUpdate {
	_u.mutation.AddCategoryDefaultEntryIDs(ids...)
	return _u
}

// AddCategoryDefaultEntries adds the "category_default_entries" edges to the CategoryDefaultFeature entity.
func (_u *FeatureUpdate) AddCategoryDefaultEntries(v ...*CategoryDefaultFeature) *FeatureUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCategoryDefaultEntryIDs(ids...)
}

// Mutation returns the FeatureMutation object of the builder.
func (_u *FeatureUpdate) Mutation() *FeatureMutation {
	return _u.mutation
}

// ClearCategoryDefaultEntries clears all "category_default_entries" edges to the CategoryDefaultFeature entity.
func (_u *FeatureUpdate) ClearCategoryDefaultEntries() *FeatureUpdate {
	_u.mutation.ClearCategoryDefaultEntries()
	return _u
}

// RemoveCategoryDefaultEntryIDs removes the "category_default_entries" edge to CategoryDefaultFeature entities by IDs.
func (_u *FeatureUpdate) RemoveCategoryDefaultEntryIDs(ids ...uint32) *FeatureUpdate {
	_u.mutation.RemoveCategoryDefaultEntryIDs(ids...)
	return _u
}

// RemoveCategoryDefaultEntries removes "category_default_entries" edges to CategoryDefaultFeature entities.
func (_u *FeatureUpdate) RemoveCategoryDefaultEntries(v ...*CategoryDefaultFeature) *FeatureUpdate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCategoryDefaultEntryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FeatureUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeatureUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FeatureUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeatureUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeatureUpdate) check() error {
	if v, ok := _u.mutation.FeatureType(); ok {
		if err := feature.FeatureTypeValidator(v); err != nil {
			return &ValidationError{Name: "feature_type", err: fmt.Errorf(`ent: validator failed for field "Feature.feature_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Identifier(); ok {
		if err := feature.IdentifierValidator(v); err != nil {
			return &ValidationError{Name: "identifier", err: fmt.Errorf(`ent: validator failed for field "Feature.identifier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := feature.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Feature.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *FeatureUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *FeatureUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *FeatureUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(feature.Table, feature.Columns, sqlgraph.NewFieldSpec(feature.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(feature.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(feature.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(feature.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(feature.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(feature.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(feature.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(feature.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(feature.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(feature.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(feature.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(feature.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(feature.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(feature.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(feature.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(feature.FieldIsEnabled, field.TypeBool, value)
	}
	if _u.mutation.IsEnabledCleared() {
		_spec.ClearField(feature.FieldIsEnabled, field.TypeBool)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(feature.FieldSortOrder, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(feature.FieldSortOrder, field.TypeUint32, value)
	}
	if _u.mutation.SortOrderCleared() {
		_spec.ClearField(feature.FieldSortOrder, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(feature.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.FeatureType(); ok {
		_spec.SetField(feature.FieldFeatureType, field.TypeEnum, value)
	}
	if _u.mutation.FeatureTypeCleared() {
		_spec.ClearField(feature.FieldFeatureType, field.TypeEnum)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(feature.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.Identifier(); ok {
		_spec.SetField(feature.FieldIdentifier, field.TypeString, value)
	}
	if _u.mutation.IdentifierCleared() {
		_spec.ClearField(feature.FieldIdentifier, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(feature.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(feature.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.NameEn(); ok {
		_spec.SetField(feature.FieldNameEn, field.TypeString, value)
	}
	if _u.mutation.NameEnCleared() {
		_spec.ClearField(feature.FieldNameEn, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(feature.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(feature.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ApplicableScope(); ok {
		_spec.SetField(feature.FieldApplicableScope, field.TypeString, value)
	}
	if _u.mutation.ApplicableScopeCleared() {
		_spec.ClearField(feature.FieldApplicableScope, field.TypeString)
	}
	if value, ok := _u.mutation.RecommendedUnitCategoryID(); ok {
		_spec.SetField(feature.FieldRecommendedUnitCategoryID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedRecommendedUnitCategoryID(); ok {
		_spec.AddField(feature.FieldRecommendedUnitCategoryID, field.TypeUint32, value)
	}
	if _u.mutation.RecommendedUnitCategoryIDCleared() {
		_spec.ClearField(feature.FieldRecommendedUnitCategoryID, field.TypeUint32)
	}
	if value, ok := _u.mutation.SemanticTag(); ok {
		_spec.SetField(feature.FieldSemanticTag, field.TypeString, value)
	}
	if _u.mutation.SemanticTagCleared() {
		_spec.ClearField(feature.FieldSemanticTag, field.TypeString)
	}
	if _u.mutation.CategoryDefaultEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feature.CategoryDefaultEntriesTable,
			Columns: []string{feature.CategoryDefaultEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categorydefaultfeature.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCategoryDefaultEntriesIDs(); len(nodes) > 0 && !_u.mutation.CategoryDefaultEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feature.CategoryDefaultEntriesTable,
			Columns: []string{feature.CategoryDefaultEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categorydefaultfeature.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryDefaultEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feature.CategoryDefaultEntriesTable,
			Columns: []string{feature.CategoryDefaultEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categorydefaultfeature.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{feature.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FeatureUpdateOne is the builder for updating a single Feature entity.
type FeatureUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *FeatureMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FeatureUpdateOne) SetUpdatedAt(v time.Time) *FeatureUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableUpdatedAt(v *time.Time) *FeatureUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *FeatureUpdateOne) ClearUpdatedAt() *FeatureUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *FeatureUpdateOne) SetDeletedAt(v time.Time) *FeatureUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableDeletedAt(v *time.Time) *FeatureUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *FeatureUpdateOne) ClearDeletedAt() *FeatureUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *FeatureUpdateOne) SetCreatedBy(v uint32) *FeatureUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableCreatedBy(v *uint32) *FeatureUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *FeatureUpdateOne) AddCreatedBy(v int32) *FeatureUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *FeatureUpdateOne) ClearCreatedBy() *FeatureUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *FeatureUpdateOne) SetUpdatedBy(v uint32) *FeatureUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableUpdatedBy(v *uint32) *FeatureUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *FeatureUpdateOne) AddUpdatedBy(v int32) *FeatureUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *FeatureUpdateOne) ClearUpdatedBy() *FeatureUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *FeatureUpdateOne) SetDeletedBy(v uint32) *FeatureUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableDeletedBy(v *uint32) *FeatureUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *FeatureUpdateOne) AddDeletedBy(v int32) *FeatureUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *FeatureUpdateOne) ClearDeletedBy() *FeatureUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *FeatureUpdateOne) SetIsEnabled(v bool) *FeatureUpdateOne {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableIsEnabled(v *bool) *FeatureUpdateOne {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (_u *FeatureUpdateOne) ClearIsEnabled() *FeatureUpdateOne {
	_u.mutation.ClearIsEnabled()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *FeatureUpdateOne) SetSortOrder(v uint32) *FeatureUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableSortOrder(v *uint32) *FeatureUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *FeatureUpdateOne) AddSortOrder(v int32) *FeatureUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (_u *FeatureUpdateOne) ClearSortOrder() *FeatureUpdateOne {
	_u.mutation.ClearSortOrder()
	return _u
}

// SetFeatureType sets the "feature_type" field.
func (_u *FeatureUpdateOne) SetFeatureType(v feature.FeatureType) *FeatureUpdateOne {
	_u.mutation.SetFeatureType(v)
	return _u
}

// SetNillableFeatureType sets the "feature_type" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableFeatureType(v *feature.FeatureType) *FeatureUpdateOne {
	if v != nil {
		_u.SetFeatureType(*v)
	}
	return _u
}

// ClearFeatureType clears the value of the "feature_type" field.
func (_u *FeatureUpdateOne) ClearFeatureType() *FeatureUpdateOne {
	_u.mutation.ClearFeatureType()
	return _u
}

// SetIdentifier sets the "identifier" field.
func (_u *FeatureUpdateOne) SetIdentifier(v string) *FeatureUpdateOne {
	_u.mutation.SetIdentifier(v)
	return _u
}

// SetNillableIdentifier sets the "identifier" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableIdentifier(v *string) *FeatureUpdateOne {
	if v != nil {
		_u.SetIdentifier(*v)
	}
	return _u
}

// ClearIdentifier clears the value of the "identifier" field.
func (_u *FeatureUpdateOne) ClearIdentifier() *FeatureUpdateOne {
	_u.mutation.ClearIdentifier()
	return _u
}

// SetName sets the "name" field.
func (_u *FeatureUpdateOne) SetName(v string) *FeatureUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableName(v *string) *FeatureUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *FeatureUpdateOne) ClearName() *FeatureUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetNameEn sets the "name_en" field.
func (_u *FeatureUpdateOne) SetNameEn(v string) *FeatureUpdateOne {
	_u.mutation.SetNameEn(v)
	return _u
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableNameEn(v *string) *FeatureUpdateOne {
	if v != nil {
		_u.SetNameEn(*v)
	}
	return _u
}

// ClearNameEn clears the value of the "name_en" field.
func (_u *FeatureUpdateOne) ClearNameEn() *FeatureUpdateOne {
	_u.mutation.ClearNameEn()
	return _u
}

// SetDescription sets the "description" field.
func (_u *FeatureUpdateOne) SetDescription(v string) *FeatureUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableDescription(v *string) *FeatureUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *FeatureUpdateOne) ClearDescription() *FeatureUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetApplicableScope sets the "applicable_scope" field.
func (_u *FeatureUpdateOne) SetApplicableScope(v string) *FeatureUpdateOne {
	_u.mutation.SetApplicableScope(v)
	return _u
}

// SetNillableApplicableScope sets the "applicable_scope" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableApplicableScope(v *string) *FeatureUpdateOne {
	if v != nil {
		_u.SetApplicableScope(*v)
	}
	return _u
}

// ClearApplicableScope clears the value of the "applicable_scope" field.
func (_u *FeatureUpdateOne) ClearApplicableScope() *FeatureUpdateOne {
	_u.mutation.ClearApplicableScope()
	return _u
}

// SetRecommendedUnitCategoryID sets the "recommended_unit_category_id" field.
func (_u *FeatureUpdateOne) SetRecommendedUnitCategoryID(v uint32) *FeatureUpdateOne {
	_u.mutation.ResetRecommendedUnitCategoryID()
	_u.mutation.SetRecommendedUnitCategoryID(v)
	return _u
}

// SetNillableRecommendedUnitCategoryID sets the "recommended_unit_category_id" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableRecommendedUnitCategoryID(v *uint32) *FeatureUpdateOne {
	if v != nil {
		_u.SetRecommendedUnitCategoryID(*v)
	}
	return _u
}

// AddRecommendedUnitCategoryID adds value to the "recommended_unit_category_id" field.
func (_u *FeatureUpdateOne) AddRecommendedUnitCategoryID(v int32) *FeatureUpdateOne {
	_u.mutation.AddRecommendedUnitCategoryID(v)
	return _u
}

// ClearRecommendedUnitCategoryID clears the value of the "recommended_unit_category_id" field.
func (_u *FeatureUpdateOne) ClearRecommendedUnitCategoryID() *FeatureUpdateOne {
	_u.mutation.ClearRecommendedUnitCategoryID()
	return _u
}

// SetSemanticTag sets the "semantic_tag" field.
func (_u *FeatureUpdateOne) SetSemanticTag(v string) *FeatureUpdateOne {
	_u.mutation.SetSemanticTag(v)
	return _u
}

// SetNillableSemanticTag sets the "semantic_tag" field if the given value is not nil.
func (_u *FeatureUpdateOne) SetNillableSemanticTag(v *string) *FeatureUpdateOne {
	if v != nil {
		_u.SetSemanticTag(*v)
	}
	return _u
}

// ClearSemanticTag clears the value of the "semantic_tag" field.
func (_u *FeatureUpdateOne) ClearSemanticTag() *FeatureUpdateOne {
	_u.mutation.ClearSemanticTag()
	return _u
}

// AddCategoryDefaultEntryIDs adds the "category_default_entries" edge to the CategoryDefaultFeature entity by IDs.
func (_u *FeatureUpdateOne) AddCategoryDefaultEntryIDs(ids ...uint32) *FeatureUpdateOne {
	_u.mutation.AddCategoryDefaultEntryIDs(ids...)
	return _u
}

// AddCategoryDefaultEntries adds the "category_default_entries" edges to the CategoryDefaultFeature entity.
func (_u *FeatureUpdateOne) AddCategoryDefaultEntries(v ...*CategoryDefaultFeature) *FeatureUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCategoryDefaultEntryIDs(ids...)
}

// Mutation returns the FeatureMutation object of the builder.
func (_u *FeatureUpdateOne) Mutation() *FeatureMutation {
	return _u.mutation
}

// ClearCategoryDefaultEntries clears all "category_default_entries" edges to the CategoryDefaultFeature entity.
func (_u *FeatureUpdateOne) ClearCategoryDefaultEntries() *FeatureUpdateOne {
	_u.mutation.ClearCategoryDefaultEntries()
	return _u
}

// RemoveCategoryDefaultEntryIDs removes the "category_default_entries" edge to CategoryDefaultFeature entities by IDs.
func (_u *FeatureUpdateOne) RemoveCategoryDefaultEntryIDs(ids ...uint32) *FeatureUpdateOne {
	_u.mutation.RemoveCategoryDefaultEntryIDs(ids...)
	return _u
}

// RemoveCategoryDefaultEntries removes "category_default_entries" edges to CategoryDefaultFeature entities.
func (_u *FeatureUpdateOne) RemoveCategoryDefaultEntries(v ...*CategoryDefaultFeature) *FeatureUpdateOne {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCategoryDefaultEntryIDs(ids...)
}

// Where appends a list predicates to the FeatureUpdate builder.
func (_u *FeatureUpdateOne) Where(ps ...predicate.Feature) *FeatureUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FeatureUpdateOne) Select(field string, fields ...string) *FeatureUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Feature entity.
func (_u *FeatureUpdateOne) Save(ctx context.Context) (*Feature, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FeatureUpdateOne) SaveX(ctx context.Context) *Feature {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FeatureUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FeatureUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FeatureUpdateOne) check() error {
	if v, ok := _u.mutation.FeatureType(); ok {
		if err := feature.FeatureTypeValidator(v); err != nil {
			return &ValidationError{Name: "feature_type", err: fmt.Errorf(`ent: validator failed for field "Feature.feature_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Identifier(); ok {
		if err := feature.IdentifierValidator(v); err != nil {
			return &ValidationError{Name: "identifier", err: fmt.Errorf(`ent: validator failed for field "Feature.identifier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := feature.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Feature.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *FeatureUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *FeatureUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *FeatureUpdateOne) sqlSave(ctx context.Context) (_node *Feature, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(feature.Table, feature.Columns, sqlgraph.NewFieldSpec(feature.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Feature.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, feature.FieldID)
		for _, f := range fields {
			if !feature.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != feature.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(feature.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(feature.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(feature.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(feature.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(feature.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(feature.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(feature.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(feature.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(feature.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(feature.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(feature.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(feature.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(feature.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(feature.FieldDeletedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(feature.FieldIsEnabled, field.TypeBool, value)
	}
	if _u.mutation.IsEnabledCleared() {
		_spec.ClearField(feature.FieldIsEnabled, field.TypeBool)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(feature.FieldSortOrder, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(feature.FieldSortOrder, field.TypeUint32, value)
	}
	if _u.mutation.SortOrderCleared() {
		_spec.ClearField(feature.FieldSortOrder, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(feature.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.FeatureType(); ok {
		_spec.SetField(feature.FieldFeatureType, field.TypeEnum, value)
	}
	if _u.mutation.FeatureTypeCleared() {
		_spec.ClearField(feature.FieldFeatureType, field.TypeEnum)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(feature.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.Identifier(); ok {
		_spec.SetField(feature.FieldIdentifier, field.TypeString, value)
	}
	if _u.mutation.IdentifierCleared() {
		_spec.ClearField(feature.FieldIdentifier, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(feature.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(feature.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.NameEn(); ok {
		_spec.SetField(feature.FieldNameEn, field.TypeString, value)
	}
	if _u.mutation.NameEnCleared() {
		_spec.ClearField(feature.FieldNameEn, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(feature.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(feature.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ApplicableScope(); ok {
		_spec.SetField(feature.FieldApplicableScope, field.TypeString, value)
	}
	if _u.mutation.ApplicableScopeCleared() {
		_spec.ClearField(feature.FieldApplicableScope, field.TypeString)
	}
	if value, ok := _u.mutation.RecommendedUnitCategoryID(); ok {
		_spec.SetField(feature.FieldRecommendedUnitCategoryID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedRecommendedUnitCategoryID(); ok {
		_spec.AddField(feature.FieldRecommendedUnitCategoryID, field.TypeUint32, value)
	}
	if _u.mutation.RecommendedUnitCategoryIDCleared() {
		_spec.ClearField(feature.FieldRecommendedUnitCategoryID, field.TypeUint32)
	}
	if value, ok := _u.mutation.SemanticTag(); ok {
		_spec.SetField(feature.FieldSemanticTag, field.TypeString, value)
	}
	if _u.mutation.SemanticTagCleared() {
		_spec.ClearField(feature.FieldSemanticTag, field.TypeString)
	}
	if _u.mutation.CategoryDefaultEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feature.CategoryDefaultEntriesTable,
			Columns: []string{feature.CategoryDefaultEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categorydefaultfeature.FieldID, field.TypeUint32),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCategoryDefaultEntriesIDs(); len(nodes) > 0 && !_u.mutation.CategoryDefaultEntriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feature.CategoryDefaultEntriesTable,
			Columns: []string{feature.CategoryDefaultEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categorydefaultfeature.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryDefaultEntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   feature.CategoryDefaultEntriesTable,
			Columns: []string{feature.CategoryDefaultEntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(categorydefaultfeature.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Feature{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{feature.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
