// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/unitcategory"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 物模型-物理量分类表 / Thing model unit category
type UnitCategory struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 是否启用
	IsEnabled *bool `json:"is_enabled,omitempty"`
	// 排序值（越小越靠前）
	SortOrder *uint32 `json:"sort_order,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 物理量编码，如 temperature/pressure（不可变）/ Category code, immutable
	Code *string `json:"code,omitempty"`
	// 中文名，如 温度 / Category name (zh)
	Name *string `json:"name,omitempty"`
	// 英文名，如 Temperature / Category name (en)
	NameEn *string `json:"name_en,omitempty"`
	// 量纲/物理量名，如 热力学温度 / Quantity
	Quantity *string `json:"quantity,omitempty"`
	// 基准单位符号（冗余展示，如 K）/ Base unit symbol (display only)
	BaseUnitSymbol *string `json:"base_unit_symbol,omitempty"`
	// Iconify 图标名 / Iconify icon name
	Icon *string `json:"icon,omitempty"`
	// 描述 / Description
	Description *string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UnitCategoryQuery when eager-loading is set.
	Edges        UnitCategoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UnitCategoryEdges holds the relations/edges for other nodes in the graph.
type UnitCategoryEdges struct {
	// Units holds the value of the units edge.
	Units []*Unit `json:"units,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UnitsOrErr returns the Units value or an error if the edge
// was not loaded in eager-loading.
func (e UnitCategoryEdges) UnitsOrErr() ([]*Unit, error) {
	if e.loadedTypes[0] {
		return e.Units, nil
	}
	return nil, &NotLoadedError{edge: "units"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UnitCategory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case unitcategory.FieldIsEnabled:
			values[i] = new(sql.NullBool)
		case unitcategory.FieldID, unitcategory.FieldCreatedBy, unitcategory.FieldUpdatedBy, unitcategory.FieldDeletedBy, unitcategory.FieldSortOrder, unitcategory.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case unitcategory.FieldCode, unitcategory.FieldName, unitcategory.FieldNameEn, unitcategory.FieldQuantity, unitcategory.FieldBaseUnitSymbol, unitcategory.FieldIcon, unitcategory.FieldDescription:
			values[i] = new(sql.NullString)
		case unitcategory.FieldCreatedAt, unitcategory.FieldUpdatedAt, unitcategory.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UnitCategory fields.
func (_m *UnitCategory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case unitcategory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case unitcategory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case unitcategory.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case unitcategory.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case unitcategory.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case unitcategory.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case unitcategory.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case unitcategory.FieldIsEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_enabled", values[i])
			} else if value.Valid {
				_m.IsEnabled = new(bool)
				*_m.IsEnabled = value.Bool
			}
		case unitcategory.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = new(uint32)
				*_m.SortOrder = uint32(value.Int64)
			}
		case unitcategory.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case unitcategory.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = new(string)
				*_m.Code = value.String
			}
		case unitcategory.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = new(string)
				*_m.Name = value.String
			}
		case unitcategory.FieldNameEn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_en", values[i])
			} else if value.Valid {
				_m.NameEn = new(string)
				*_m.NameEn = value.String
			}
		case unitcategory.FieldQuantity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = new(string)
				*_m.Quantity = value.String
			}
		case unitcategory.FieldBaseUnitSymbol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_unit_symbol", values[i])
			} else if value.Valid {
				_m.BaseUnitSymbol = new(string)
				*_m.BaseUnitSymbol = value.String
			}
		case unitcategory.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				_m.Icon = new(string)
				*_m.Icon = value.String
			}
		case unitcategory.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UnitCategory.
// This includes values selected through modifiers, order, etc.
func (_m *UnitCategory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUnits queries the "units" edge of the UnitCategory entity.
func (_m *UnitCategory) QueryUnits() *UnitQuery {
	return NewUnitCategoryClient(_m.config).QueryUnits(_m)
}

// Update returns a builder for updating this UnitCategory.
// Note that you need to call UnitCategory.Unwrap() before calling this method if this UnitCategory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UnitCategory) Update() *UnitCategoryUpdateOne {
	return NewUnitCategoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UnitCategory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UnitCategory) Unwrap() *UnitCategory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UnitCategory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UnitCategory) String() string {
	var builder strings.Builder
	builder.WriteString("UnitCategory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.IsEnabled; v != nil {
		builder.WriteString("is_enabled=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SortOrder; v != nil {
		builder.WriteString("sort_order=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Code; v != nil {
		builder.WriteString("code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.NameEn; v != nil {
		builder.WriteString("name_en=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Quantity; v != nil {
		builder.WriteString("quantity=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BaseUnitSymbol; v != nil {
		builder.WriteString("base_unit_symbol=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Icon; v != nil {
		builder.WriteString("icon=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// UnitCategories is a parsable slice of UnitCategory.
type UnitCategories []*UnitCategory
