// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/unit"
	"go-wind-admin/app/admin/service/internal/data/ent/unitcategory"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 物模型-单位表 / Thing model unit
type Unit struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 排序值（越小越靠前）
	SortOrder *uint32 `json:"sort_order,omitempty"`
	// 是否启用
	IsEnabled *bool `json:"is_enabled,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 所属物理量分类ID / Category ID
	CategoryID *uint32 `json:"category_id,omitempty"`
	// 单位编码，如 celsius（不可变）/ Unit code, immutable
	Code *string `json:"code,omitempty"`
	// 单位符号，如 ℃ / Unit symbol
	Symbol *string `json:"symbol,omitempty"`
	// 中文名 / Unit name (zh)
	Name *string `json:"name,omitempty"`
	// 英文名 / Unit name (en)
	NameEn *string `json:"name_en,omitempty"`
	// 是否基准单位（每分类唯一）/ Is base unit
	IsBase *bool `json:"is_base,omitempty"`
	// 换算类型 / Conversion type
	ConversionType *unit.ConversionType `json:"conversion_type,omitempty"`
	// 线性系数 k（基准=原值·k+offset）/ Linear factor k
	Factor *float64 `json:"factor,omitempty"`
	// 偏移量 b（仅仿射非0）/ Offset b (affine only)
	Offset *float64 `json:"offset,omitempty"`
	// 公式说明（仅展示）/ Formula description (display only)
	FormulaExpr *string `json:"formula_expr,omitempty"`
	// 建议显示精度（小数位）/ Display precision
	Precision *int32 `json:"precision,omitempty"`
	// 是否 SI 单位 / Is SI unit
	IsSiUnit *bool `json:"is_si_unit,omitempty"`
	// 是否中国法定计量单位 / Is PRC legal unit
	IsLegalUnit *bool `json:"is_legal_unit,omitempty"`
	// 被物模型属性引用次数（预留）/ Reference count (reserved)
	ReferenceCount *uint32 `json:"reference_count,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UnitQuery when eager-loading is set.
	Edges        UnitEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UnitEdges holds the relations/edges for other nodes in the graph.
type UnitEdges struct {
	// Category holds the value of the category edge.
	Category *UnitCategory `json:"category,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UnitEdges) CategoryOrErr() (*UnitCategory, error) {
	if e.Category != nil {
		return e.Category, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: unitcategory.Label}
	}
	return nil, &NotLoadedError{edge: "category"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Unit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case unit.FieldIsEnabled, unit.FieldIsBase, unit.FieldIsSiUnit, unit.FieldIsLegalUnit:
			values[i] = new(sql.NullBool)
		case unit.FieldFactor, unit.FieldOffset:
			values[i] = new(sql.NullFloat64)
		case unit.FieldID, unit.FieldCreatedBy, unit.FieldUpdatedBy, unit.FieldDeletedBy, unit.FieldSortOrder, unit.FieldTenantID, unit.FieldCategoryID, unit.FieldPrecision, unit.FieldReferenceCount:
			values[i] = new(sql.NullInt64)
		case unit.FieldCode, unit.FieldSymbol, unit.FieldName, unit.FieldNameEn, unit.FieldConversionType, unit.FieldFormulaExpr:
			values[i] = new(sql.NullString)
		case unit.FieldCreatedAt, unit.FieldUpdatedAt, unit.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Unit fields.
func (_m *Unit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case unit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case unit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case unit.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case unit.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case unit.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case unit.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case unit.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case unit.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = new(uint32)
				*_m.SortOrder = uint32(value.Int64)
			}
		case unit.FieldIsEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_enabled", values[i])
			} else if value.Valid {
				_m.IsEnabled = new(bool)
				*_m.IsEnabled = value.Bool
			}
		case unit.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case unit.FieldCategoryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field category_id", values[i])
			} else if value.Valid {
				_m.CategoryID = new(uint32)
				*_m.CategoryID = uint32(value.Int64)
			}
		case unit.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = new(string)
				*_m.Code = value.String
			}
		case unit.FieldSymbol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field symbol", values[i])
			} else if value.Valid {
				_m.Symbol = new(string)
				*_m.Symbol = value.String
			}
		case unit.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = new(string)
				*_m.Name = value.String
			}
		case unit.FieldNameEn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_en", values[i])
			} else if value.Valid {
				_m.NameEn = new(string)
				*_m.NameEn = value.String
			}
		case unit.FieldIsBase:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_base", values[i])
			} else if value.Valid {
				_m.IsBase = new(bool)
				*_m.IsBase = value.Bool
			}
		case unit.FieldConversionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field conversion_type", values[i])
			} else if value.Valid {
				_m.ConversionType = new(unit.ConversionType)
				*_m.ConversionType = unit.ConversionType(value.String)
			}
		case unit.FieldFactor:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field factor", values[i])
			} else if value.Valid {
				_m.Factor = new(float64)
				*_m.Factor = value.Float64
			}
		case unit.FieldOffset:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field offset", values[i])
			} else if value.Valid {
				_m.Offset = new(float64)
				*_m.Offset = value.Float64
			}
		case unit.FieldFormulaExpr:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field formula_expr", values[i])
			} else if value.Valid {
				_m.FormulaExpr = new(string)
				*_m.FormulaExpr = value.String
			}
		case unit.FieldPrecision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field precision", values[i])
			} else if value.Valid {
				_m.Precision = new(int32)
				*_m.Precision = int32(value.Int64)
			}
		case unit.FieldIsSiUnit:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_si_unit", values[i])
			} else if value.Valid {
				_m.IsSiUnit = new(bool)
				*_m.IsSiUnit = value.Bool
			}
		case unit.FieldIsLegalUnit:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_legal_unit", values[i])
			} else if value.Valid {
				_m.IsLegalUnit = new(bool)
				*_m.IsLegalUnit = value.Bool
			}
		case unit.FieldReferenceCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reference_count", values[i])
			} else if value.Valid {
				_m.ReferenceCount = new(uint32)
				*_m.ReferenceCount = uint32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Unit.
// This includes values selected through modifiers, order, etc.
func (_m *Unit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCategory queries the "category" edge of the Unit entity.
func (_m *Unit) QueryCategory() *UnitCategoryQuery {
	return NewUnitClient(_m.config).QueryCategory(_m)
}

// Update returns a builder for updating this Unit.
// Note that you need to call Unit.Unwrap() before calling this method if this Unit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Unit) Update() *UnitUpdateOne {
	return NewUnitClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Unit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Unit) Unwrap() *Unit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Unit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Unit) String() string {
	var builder strings.Builder
	builder.WriteString("Unit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SortOrder; v != nil {
		builder.WriteString("sort_order=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.IsEnabled; v != nil {
		builder.WriteString("is_enabled=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CategoryID; v != nil {
		builder.WriteString("category_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Code; v != nil {
		builder.WriteString("code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Symbol; v != nil {
		builder.WriteString("symbol=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.NameEn; v != nil {
		builder.WriteString("name_en=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IsBase; v != nil {
		builder.WriteString("is_base=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ConversionType; v != nil {
		builder.WriteString("conversion_type=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Factor; v != nil {
		builder.WriteString("factor=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Offset; v != nil {
		builder.WriteString("offset=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.FormulaExpr; v != nil {
		builder.WriteString("formula_expr=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Precision; v != nil {
		builder.WriteString("precision=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.IsSiUnit; v != nil {
		builder.WriteString("is_si_unit=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.IsLegalUnit; v != nil {
		builder.WriteString("is_legal_unit=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ReferenceCount; v != nil {
		builder.WriteString("reference_count=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Units is a parsable slice of Unit.
type Units []*Unit
