// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/unit"
	"go-wind-admin/app/admin/service/internal/data/ent/unitcategory"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UnitCategoryCreate is the builder for creating a UnitCategory entity.
type UnitCategoryCreate struct {
	config
	mutation *UnitCategoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UnitCategoryCreate) SetCreatedAt(v time.Time) *UnitCategoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UnitCategoryCreate) SetNillableCreatedAt(v *time.Time) *UnitCategoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UnitCategoryCreate) SetUpdatedAt(v time.Time) *UnitCategoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UnitCategoryCreate) SetNillableUpdatedAt(v *time.Time) *UnitCategoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UnitCategoryCreate) SetDeletedAt(v time.Time) *UnitCategoryCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UnitCategoryCreate) SetNillableDeletedAt(v *time.Time) *UnitCategoryCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *UnitCategoryCreate) SetCreatedBy(v uint32) *UnitCategoryCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *UnitCategoryCreate) SetNillableCreatedBy(v *uint32) *UnitCategoryCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *UnitCategoryCreate) SetUpdatedBy(v uint32) *UnitCategoryCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *UnitCategoryCreate) SetNillableUpdatedBy(v *uint32) *UnitCategoryCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *UnitCategoryCreate) SetDeletedBy(v uint32) *UnitCategoryCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *UnitCategoryCreate) SetNillableDeletedBy(v *uint32) *UnitCategoryCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetIsEnabled sets the "is_enabled" field.
func (_c *UnitCategoryCreate) SetIsEnabled(v bool) *UnitCategoryCreate {
	_c.mutation.SetIsEnabled(v)
	return _c
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_c *UnitCategoryCreate) SetNillableIsEnabled(v *bool) *UnitCategoryCreate {
	if v != nil {
		_c.SetIsEnabled(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *UnitCategoryCreate) SetSortOrder(v uint32) *UnitCategoryCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *UnitCategoryCreate) SetNillableSortOrder(v *uint32) *UnitCategoryCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *UnitCategoryCreate) SetTenantID(v uint32) *UnitCategoryCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *UnitCategoryCreate) SetNillableTenantID(v *uint32) *UnitCategoryCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *UnitCategoryCreate) SetCode(v string) *UnitCategoryCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_c *UnitCategoryCreate) SetNillableCode(v *string) *UnitCategoryCreate {
	if v != nil {
		_c.SetCode(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *UnitCategoryCreate) SetName(v string) *UnitCategoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *UnitCategoryCreate) SetNillableName(v *string) *UnitCategoryCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetNameEn sets the "name_en" field.
func (_c *UnitCategoryCreate) SetNameEn(v string) *UnitCategoryCreate {
	_c.mutation.SetNameEn(v)
	return _c
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (_c *UnitCategoryCreate) SetNillableNameEn(v *string) *UnitCategoryCreate {
	if v != nil {
		_c.SetNameEn(*v)
	}
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *UnitCategoryCreate) SetQuantity(v string) *UnitCategoryCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_c *UnitCategoryCreate) SetNillableQuantity(v *string) *UnitCategoryCreate {
	if v != nil {
		_c.SetQuantity(*v)
	}
	return _c
}

// SetBaseUnitSymbol sets the "base_unit_symbol" field.
func (_c *UnitCategoryCreate) SetBaseUnitSymbol(v string) *UnitCategoryCreate {
	_c.mutation.SetBaseUnitSymbol(v)
	return _c
}

// SetNillableBaseUnitSymbol sets the "base_unit_symbol" field if the given value is not nil.
func (_c *UnitCategoryCreate) SetNillableBaseUnitSymbol(v *string) *UnitCategoryCreate {
	if v != nil {
		_c.SetBaseUnitSymbol(*v)
	}
	return _c
}

// SetIcon sets the "icon" field.
func (_c *UnitCategoryCreate) SetIcon(v string) *UnitCategoryCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *UnitCategoryCreate) SetNillableIcon(v *string) *UnitCategoryCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *UnitCategoryCreate) SetDescription(v string) *UnitCategoryCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *UnitCategoryCreate) SetNillableDescription(v *string) *UnitCategoryCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UnitCategoryCreate) SetID(v uint32) *UnitCategoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddUnitIDs adds the "units" edge to the Unit entity by IDs.
func (_c *UnitCategoryCreate) AddUnitIDs(ids ...uint32) *UnitCategoryCreate {
	_c.mutation.AddUnitIDs(ids...)
	return _c
}

// AddUnits adds the "units" edges to the Unit entity.
func (_c *UnitCategoryCreate) AddUnits(v ...*Unit) *UnitCategoryCreate {
	ids := make([]uint32, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUnitIDs(ids...)
}

// Mutation returns the UnitCategoryMutation object of the builder.
func (_c *UnitCategoryCreate) Mutation() *UnitCategoryMutation {
	return _c.mutation
}

// Save creates the UnitCategory in the database.
func (_c *UnitCategoryCreate) Save(ctx context.Context) (*UnitCategory, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UnitCategoryCreate) SaveX(ctx context.Context) *UnitCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UnitCategoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UnitCategoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UnitCategoryCreate) defaults() error {
	if _, ok := _c.mutation.IsEnabled(); !ok {
		v := unitcategory.DefaultIsEnabled
		_c.mutation.SetIsEnabled(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := unitcategory.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := unitcategory.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UnitCategoryCreate) check() error {
	if v, ok := _c.mutation.Code(); ok {
		if err := unitcategory.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "UnitCategory.code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := unitcategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UnitCategory.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := unitcategory.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "UnitCategory.id": %w`, err)}
		}
	}
	return nil
}

func (_c *UnitCategoryCreate) sqlSave(ctx context.Context) (*UnitCategory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UnitCategoryCreate) createSpec() (*UnitCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &UnitCategory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(unitcategory.Table, sqlgraph.NewFieldSpec(unitcategory.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(unitcategory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(unitcategory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(unitcategory.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(unitcategory.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(unitcategory.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(unitcategory.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.IsEnabled(); ok {
		_spec.SetField(unitcategory.FieldIsEnabled, field.TypeBool, value)
		_node.IsEnabled = &value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(unitcategory.FieldSortOrder, field.TypeUint32, value)
		_node.SortOrder = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(unitcategory.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(unitcategory.FieldCode, field.TypeString, value)
		_node.Code = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(unitcategory.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	if value, ok := _c.mutation.NameEn(); ok {
		_spec.SetField(unitcategory.FieldNameEn, field.TypeString, value)
		_node.NameEn = &value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(unitcategory.FieldQuantity, field.TypeString, value)
		_node.Quantity = &value
	}
	if value, ok := _c.mutation.BaseUnitSymbol(); ok {
		_spec.SetField(unitcategory.FieldBaseUnitSymbol, field.TypeString, value)
		_node.BaseUnitSymbol = &value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(unitcategory.FieldIcon, field.TypeString, value)
		_node.Icon = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(unitcategory.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if nodes := _c.mutation.UnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unitcategory.UnitsTable,
			Columns: []string{unitcategory.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UnitCategory.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UnitCategoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UnitCategoryCreate) OnConflict(opts ...sql.ConflictOption) *UnitCategoryUpsertOne {
	_c.conflict = opts
	return &UnitCategoryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UnitCategory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UnitCategoryCreate) OnConflictColumns(columns ...string) *UnitCategoryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UnitCategoryUpsertOne{
		create: _c,
	}
}

type (
	// UnitCategoryUpsertOne is the builder for "upsert"-ing
	//  one UnitCategory node.
	UnitCategoryUpsertOne struct {
		create *UnitCategoryCreate
	}

	// UnitCategoryUpsert is the "OnConflict" setter.
	UnitCategoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UnitCategoryUpsert) SetUpdatedAt(v time.Time) *UnitCategoryUpsert {
	u.Set(unitcategory.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UnitCategoryUpsert) UpdateUpdatedAt() *UnitCategoryUpsert {
	u.SetExcluded(unitcategory.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *UnitCategoryUpsert) ClearUpdatedAt() *UnitCategoryUpsert {
	u.SetNull(unitcategory.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UnitCategoryUpsert) SetDeletedAt(v time.Time) *UnitCategoryUpsert {
	u.Set(unitcategory.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UnitCategoryUpsert) UpdateDeletedAt() *UnitCategoryUpsert {
	u.SetExcluded(unitcategory.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UnitCategoryUpsert) ClearDeletedAt() *UnitCategoryUpsert {
	u.SetNull(unitcategory.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *UnitCategoryUpsert) SetCreatedBy(v uint32) *UnitCategoryUpsert {
	u.Set(unitcategory.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *UnitCategoryUpsert) UpdateCreatedBy() *UnitCategoryUpsert {
	u.SetExcluded(unitcategory.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *UnitCategoryUpsert) AddCreatedBy(v uint32) *UnitCategoryUpsert {
	u.Add(unitcategory.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *UnitCategoryUpsert) ClearCreatedBy() *UnitCategoryUpsert {
	u.SetNull(unitcategory.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *UnitCategoryUpsert) SetUpdatedBy(v uint32) *UnitCategoryUpsert {
	u.Set(unitcategory.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *UnitCategoryUpsert) UpdateUpdatedBy() *UnitCategoryUpsert {
	u.SetExcluded(unitcategory.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *UnitCategoryUpsert) AddUpdatedBy(v uint32) *UnitCategoryUpsert {
	u.Add(unitcategory.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *UnitCategoryUpsert) ClearUpdatedBy() *UnitCategoryUpsert {
	u.SetNull(unitcategory.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *UnitCategoryUpsert) SetDeletedBy(v uint32) *UnitCategoryUpsert {
	u.Set(unitcategory.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *UnitCategoryUpsert) UpdateDeletedBy() *UnitCategoryUpsert {
	u.SetExcluded(unitcategory.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *UnitCategoryUpsert) AddDeletedBy(v uint32) *UnitCategoryUpsert {
	u.Add(unitcategory.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *UnitCategoryUpsert) ClearDeletedBy() *UnitCategoryUpsert {
	u.SetNull(unitcategory.FieldDeletedBy)
	return u
}

// SetIsEnabled sets the "is_enabled" field.
func (u *UnitCategoryUpsert) SetIsEnabled(v bool) *UnitCategoryUpsert {
	u.Set(unitcategory.FieldIsEnabled, v)
	return u
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *UnitCategoryUpsert) UpdateIsEnabled() *UnitCategoryUpsert {
	u.SetExcluded(unitcategory.FieldIsEnabled)
	return u
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (u *UnitCategoryUpsert) ClearIsEnabled() *UnitCategoryUpsert {
	u.SetNull(unitcategory.FieldIsEnabled)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *UnitCategoryUpsert) SetSortOrder(v uint32) *UnitCategoryUpsert {
	u.Set(unitcategory.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *UnitCategoryUpsert) UpdateSortOrder() *UnitCategoryUpsert {
	u.SetExcluded(unitcategory.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *UnitCategoryUpsert) AddSortOrder(v uint32) *UnitCategoryUpsert {
	u.Add(unitcategory.FieldSortOrder, v)
	return u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (u *UnitCategoryUpsert) ClearSortOrder() *UnitCategoryUpsert {
	u.SetNull(unitcategory.FieldSortOrder)
	return u
}

// SetName sets the "name" field.
func (u *UnitCategoryUpsert) SetName(v string) *UnitCategoryUpsert {
	u.Set(unitcategory.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UnitCategoryUpsert) UpdateName() *UnitCategoryUpsert {
	u.SetExcluded(unitcategory.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *UnitCategoryUpsert) ClearName() *UnitCategoryUpsert {
	u.SetNull(unitcategory.FieldName)
	return u
}

// SetNameEn sets the "name_en" field.
func (u *UnitCategoryUpsert) SetNameEn(v string) *UnitCategoryUpsert {
	u.Set(unitcategory.FieldNameEn, v)
	return u
}

// UpdateNameEn sets the "name_en" field to the value that was provided on create.
func (u *UnitCategoryUpsert) UpdateNameEn() *UnitCategoryUpsert {
	u.SetExcluded(unitcategory.FieldNameEn)
	return u
}

// ClearNameEn clears the value of the "name_en" field.
func (u *UnitCategoryUpsert) ClearNameEn() *UnitCategoryUpsert {
	u.SetNull(unitcategory.FieldNameEn)
	return u
}

// SetQuantity sets the "quantity" field.
func (u *UnitCategoryUpsert) SetQuantity(v string) *UnitCategoryUpsert {
	u.Set(unitcategory.FieldQuantity, v)
	return u
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *UnitCategoryUpsert) UpdateQuantity() *UnitCategoryUpsert {
	u.SetExcluded(unitcategory.FieldQuantity)
	return u
}

// ClearQuantity clears the value of the "quantity" field.
func (u *UnitCategoryUpsert) ClearQuantity() *UnitCategoryUpsert {
	u.SetNull(unitcategory.FieldQuantity)
	return u
}

// SetBaseUnitSymbol sets the "base_unit_symbol" field.
func (u *UnitCategoryUpsert) SetBaseUnitSymbol(v string) *UnitCategoryUpsert {
	u.Set(unitcategory.FieldBaseUnitSymbol, v)
	return u
}

// UpdateBaseUnitSymbol sets the "base_unit_symbol" field to the value that was provided on create.
func (u *UnitCategoryUpsert) UpdateBaseUnitSymbol() *UnitCategoryUpsert {
	u.SetExcluded(unitcategory.FieldBaseUnitSymbol)
	return u
}

// ClearBaseUnitSymbol clears the value of the "base_unit_symbol" field.
func (u *UnitCategoryUpsert) ClearBaseUnitSymbol() *UnitCategoryUpsert {
	u.SetNull(unitcategory.FieldBaseUnitSymbol)
	return u
}

// SetIcon sets the "icon" field.
func (u *UnitCategoryUpsert) SetIcon(v string) *UnitCategoryUpsert {
	u.Set(unitcategory.FieldIcon, v)
	return u
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *UnitCategoryUpsert) UpdateIcon() *UnitCategoryUpsert {
	u.SetExcluded(unitcategory.FieldIcon)
	return u
}

// ClearIcon clears the value of the "icon" field.
func (u *UnitCategoryUpsert) ClearIcon() *UnitCategoryUpsert {
	u.SetNull(unitcategory.FieldIcon)
	return u
}

// SetDescription sets the "description" field.
func (u *UnitCategoryUpsert) SetDescription(v string) *UnitCategoryUpsert {
	u.Set(unitcategory.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *UnitCategoryUpsert) UpdateDescription() *UnitCategoryUpsert {
	u.SetExcluded(unitcategory.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *UnitCategoryUpsert) ClearDescription() *UnitCategoryUpsert {
	u.SetNull(unitcategory.FieldDescription)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UnitCategory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(unitcategory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UnitCategoryUpsertOne) UpdateNewValues() *UnitCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(unitcategory.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(unitcategory.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(unitcategory.FieldTenantID)
		}
		if _, exists := u.create.mutation.Code(); exists {
			s.SetIgnore(unitcategory.FieldCode)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UnitCategory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UnitCategoryUpsertOne) Ignore() *UnitCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UnitCategoryUpsertOne) DoNothing() *UnitCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UnitCategoryCreate.OnConflict
// documentation for more info.
func (u *UnitCategoryUpsertOne) Update(set func(*UnitCategoryUpsert)) *UnitCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UnitCategoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UnitCategoryUpsertOne) SetUpdatedAt(v time.Time) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UnitCategoryUpsertOne) UpdateUpdatedAt() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *UnitCategoryUpsertOne) ClearUpdatedAt() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UnitCategoryUpsertOne) SetDeletedAt(v time.Time) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UnitCategoryUpsertOne) UpdateDeletedAt() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UnitCategoryUpsertOne) ClearDeletedAt() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *UnitCategoryUpsertOne) SetCreatedBy(v uint32) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *UnitCategoryUpsertOne) AddCreatedBy(v uint32) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *UnitCategoryUpsertOne) UpdateCreatedBy() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *UnitCategoryUpsertOne) ClearCreatedBy() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *UnitCategoryUpsertOne) SetUpdatedBy(v uint32) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *UnitCategoryUpsertOne) AddUpdatedBy(v uint32) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *UnitCategoryUpsertOne) UpdateUpdatedBy() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *UnitCategoryUpsertOne) ClearUpdatedBy() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *UnitCategoryUpsertOne) SetDeletedBy(v uint32) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *UnitCategoryUpsertOne) AddDeletedBy(v uint32) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *UnitCategoryUpsertOne) UpdateDeletedBy() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *UnitCategoryUpsertOne) ClearDeletedBy() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearDeletedBy()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *UnitCategoryUpsertOne) SetIsEnabled(v bool) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *UnitCategoryUpsertOne) UpdateIsEnabled() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateIsEnabled()
	})
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (u *UnitCategoryUpsertOne) ClearIsEnabled() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearIsEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *UnitCategoryUpsertOne) SetSortOrder(v uint32) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *UnitCategoryUpsertOne) AddSortOrder(v uint32) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *UnitCategoryUpsertOne) UpdateSortOrder() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateSortOrder()
	})
}

// ClearSortOrder clears the value of the "sort_order" field.
func (u *UnitCategoryUpsertOne) ClearSortOrder() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearSortOrder()
	})
}

// SetName sets the "name" field.
func (u *UnitCategoryUpsertOne) SetName(v string) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UnitCategoryUpsertOne) UpdateName() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *UnitCategoryUpsertOne) ClearName() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearName()
	})
}

// SetNameEn sets the "name_en" field.
func (u *UnitCategoryUpsertOne) SetNameEn(v string) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetNameEn(v)
	})
}

// UpdateNameEn sets the "name_en" field to the value that was provided on create.
func (u *UnitCategoryUpsertOne) UpdateNameEn() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateNameEn()
	})
}

// ClearNameEn clears the value of the "name_en" field.
func (u *UnitCategoryUpsertOne) ClearNameEn() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearNameEn()
	})
}

// SetQuantity sets the "quantity" field.
func (u *UnitCategoryUpsertOne) SetQuantity(v string) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *UnitCategoryUpsertOne) UpdateQuantity() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateQuantity()
	})
}

// ClearQuantity clears the value of the "quantity" field.
func (u *UnitCategoryUpsertOne) ClearQuantity() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearQuantity()
	})
}

// SetBaseUnitSymbol sets the "base_unit_symbol" field.
func (u *UnitCategoryUpsertOne) SetBaseUnitSymbol(v string) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetBaseUnitSymbol(v)
	})
}

// UpdateBaseUnitSymbol sets the "base_unit_symbol" field to the value that was provided on create.
func (u *UnitCategoryUpsertOne) UpdateBaseUnitSymbol() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateBaseUnitSymbol()
	})
}

// ClearBaseUnitSymbol clears the value of the "base_unit_symbol" field.
func (u *UnitCategoryUpsertOne) ClearBaseUnitSymbol() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearBaseUnitSymbol()
	})
}

// SetIcon sets the "icon" field.
func (u *UnitCategoryUpsertOne) SetIcon(v string) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *UnitCategoryUpsertOne) UpdateIcon() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateIcon()
	})
}

// ClearIcon clears the value of the "icon" field.
func (u *UnitCategoryUpsertOne) ClearIcon() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearIcon()
	})
}

// SetDescription sets the "description" field.
func (u *UnitCategoryUpsertOne) SetDescription(v string) *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *UnitCategoryUpsertOne) UpdateDescription() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *UnitCategoryUpsertOne) ClearDescription() *UnitCategoryUpsertOne {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *UnitCategoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UnitCategoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UnitCategoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UnitCategoryUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UnitCategoryUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UnitCategoryCreateBulk is the builder for creating many UnitCategory entities in bulk.
type UnitCategoryCreateBulk struct {
	config
	err      error
	builders []*UnitCategoryCreate
	conflict []sql.ConflictOption
}

// Save creates the UnitCategory entities in the database.
func (_c *UnitCategoryCreateBulk) Save(ctx context.Context) ([]*UnitCategory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UnitCategory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UnitCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UnitCategoryCreateBulk) SaveX(ctx context.Context) []*UnitCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UnitCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UnitCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UnitCategory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UnitCategoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UnitCategoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *UnitCategoryUpsertBulk {
	_c.conflict = opts
	return &UnitCategoryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UnitCategory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UnitCategoryCreateBulk) OnConflictColumns(columns ...string) *UnitCategoryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UnitCategoryUpsertBulk{
		create: _c,
	}
}

// UnitCategoryUpsertBulk is the builder for "upsert"-ing
// a bulk of UnitCategory nodes.
type UnitCategoryUpsertBulk struct {
	create *UnitCategoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UnitCategory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(unitcategory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UnitCategoryUpsertBulk) UpdateNewValues() *UnitCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(unitcategory.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(unitcategory.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(unitcategory.FieldTenantID)
			}
			if _, exists := b.mutation.Code(); exists {
				s.SetIgnore(unitcategory.FieldCode)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UnitCategory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UnitCategoryUpsertBulk) Ignore() *UnitCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UnitCategoryUpsertBulk) DoNothing() *UnitCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UnitCategoryCreateBulk.OnConflict
// documentation for more info.
func (u *UnitCategoryUpsertBulk) Update(set func(*UnitCategoryUpsert)) *UnitCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UnitCategoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UnitCategoryUpsertBulk) SetUpdatedAt(v time.Time) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UnitCategoryUpsertBulk) UpdateUpdatedAt() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *UnitCategoryUpsertBulk) ClearUpdatedAt() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UnitCategoryUpsertBulk) SetDeletedAt(v time.Time) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UnitCategoryUpsertBulk) UpdateDeletedAt() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UnitCategoryUpsertBulk) ClearDeletedAt() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *UnitCategoryUpsertBulk) SetCreatedBy(v uint32) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *UnitCategoryUpsertBulk) AddCreatedBy(v uint32) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *UnitCategoryUpsertBulk) UpdateCreatedBy() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *UnitCategoryUpsertBulk) ClearCreatedBy() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *UnitCategoryUpsertBulk) SetUpdatedBy(v uint32) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *UnitCategoryUpsertBulk) AddUpdatedBy(v uint32) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *UnitCategoryUpsertBulk) UpdateUpdatedBy() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *UnitCategoryUpsertBulk) ClearUpdatedBy() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *UnitCategoryUpsertBulk) SetDeletedBy(v uint32) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *UnitCategoryUpsertBulk) AddDeletedBy(v uint32) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *UnitCategoryUpsertBulk) UpdateDeletedBy() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *UnitCategoryUpsertBulk) ClearDeletedBy() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearDeletedBy()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *UnitCategoryUpsertBulk) SetIsEnabled(v bool) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *UnitCategoryUpsertBulk) UpdateIsEnabled() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateIsEnabled()
	})
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (u *UnitCategoryUpsertBulk) ClearIsEnabled() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearIsEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *UnitCategoryUpsertBulk) SetSortOrder(v uint32) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *UnitCategoryUpsertBulk) AddSortOrder(v uint32) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *UnitCategoryUpsertBulk) UpdateSortOrder() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateSortOrder()
	})
}

// ClearSortOrder clears the value of the "sort_order" field.
func (u *UnitCategoryUpsertBulk) ClearSortOrder() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearSortOrder()
	})
}

// SetName sets the "name" field.
func (u *UnitCategoryUpsertBulk) SetName(v string) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UnitCategoryUpsertBulk) UpdateName() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *UnitCategoryUpsertBulk) ClearName() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearName()
	})
}

// SetNameEn sets the "name_en" field.
func (u *UnitCategoryUpsertBulk) SetNameEn(v string) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetNameEn(v)
	})
}

// UpdateNameEn sets the "name_en" field to the value that was provided on create.
func (u *UnitCategoryUpsertBulk) UpdateNameEn() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateNameEn()
	})
}

// ClearNameEn clears the value of the "name_en" field.
func (u *UnitCategoryUpsertBulk) ClearNameEn() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearNameEn()
	})
}

// SetQuantity sets the "quantity" field.
func (u *UnitCategoryUpsertBulk) SetQuantity(v string) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *UnitCategoryUpsertBulk) UpdateQuantity() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateQuantity()
	})
}

// ClearQuantity clears the value of the "quantity" field.
func (u *UnitCategoryUpsertBulk) ClearQuantity() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearQuantity()
	})
}

// SetBaseUnitSymbol sets the "base_unit_symbol" field.
func (u *UnitCategoryUpsertBulk) SetBaseUnitSymbol(v string) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetBaseUnitSymbol(v)
	})
}

// UpdateBaseUnitSymbol sets the "base_unit_symbol" field to the value that was provided on create.
func (u *UnitCategoryUpsertBulk) UpdateBaseUnitSymbol() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateBaseUnitSymbol()
	})
}

// ClearBaseUnitSymbol clears the value of the "base_unit_symbol" field.
func (u *UnitCategoryUpsertBulk) ClearBaseUnitSymbol() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearBaseUnitSymbol()
	})
}

// SetIcon sets the "icon" field.
func (u *UnitCategoryUpsertBulk) SetIcon(v string) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetIcon(v)
	})
}

// UpdateIcon sets the "icon" field to the value that was provided on create.
func (u *UnitCategoryUpsertBulk) UpdateIcon() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateIcon()
	})
}

// ClearIcon clears the value of the "icon" field.
func (u *UnitCategoryUpsertBulk) ClearIcon() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearIcon()
	})
}

// SetDescription sets the "description" field.
func (u *UnitCategoryUpsertBulk) SetDescription(v string) *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *UnitCategoryUpsertBulk) UpdateDescription() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *UnitCategoryUpsertBulk) ClearDescription() *UnitCategoryUpsertBulk {
	return u.Update(func(s *UnitCategoryUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *UnitCategoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UnitCategoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UnitCategoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UnitCategoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
