// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"go-wind-admin/app/admin/service/internal/data/ent/unit"
	"go-wind-admin/app/admin/service/internal/data/ent/unitcategory"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UnitCategoryQuery is the builder for querying UnitCategory entities.
type UnitCategoryQuery struct {
	config
	ctx        *QueryContext
	order      []unitcategory.OrderOption
	inters     []Interceptor
	predicates []predicate.UnitCategory
	withUnits  *UnitQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UnitCategoryQuery builder.
func (_q *UnitCategoryQuery) Where(ps ...predicate.UnitCategory) *UnitCategoryQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *UnitCategoryQuery) Limit(limit int) *UnitCategoryQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *UnitCategoryQuery) Offset(offset int) *UnitCategoryQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *UnitCategoryQuery) Unique(unique bool) *UnitCategoryQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *UnitCategoryQuery) Order(o ...unitcategory.OrderOption) *UnitCategoryQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUnits chains the current query on the "units" edge.
func (_q *UnitCategoryQuery) QueryUnits() *UnitQuery {
	query := (&UnitClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(unitcategory.Table, unitcategory.FieldID, selector),
			sqlgraph.To(unit.Table, unit.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, unitcategory.UnitsTable, unitcategory.UnitsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UnitCategory entity from the query.
// Returns a *NotFoundError when no UnitCategory was found.
func (_q *UnitCategoryQuery) First(ctx context.Context) (*UnitCategory, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{unitcategory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *UnitCategoryQuery) FirstX(ctx context.Context) *UnitCategory {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UnitCategory ID from the query.
// Returns a *NotFoundError when no UnitCategory ID was found.
func (_q *UnitCategoryQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{unitcategory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *UnitCategoryQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UnitCategory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UnitCategory entity is found.
// Returns a *NotFoundError when no UnitCategory entities are found.
func (_q *UnitCategoryQuery) Only(ctx context.Context) (*UnitCategory, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{unitcategory.Label}
	default:
		return nil, &NotSingularError{unitcategory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *UnitCategoryQuery) OnlyX(ctx context.Context) *UnitCategory {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UnitCategory ID in the query.
// Returns a *NotSingularError when more than one UnitCategory ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *UnitCategoryQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{unitcategory.Label}
	default:
		err = &NotSingularError{unitcategory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *UnitCategoryQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UnitCategories.
func (_q *UnitCategoryQuery) All(ctx context.Context) ([]*UnitCategory, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UnitCategory, *UnitCategoryQuery]()
	return withInterceptors[[]*UnitCategory](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *UnitCategoryQuery) AllX(ctx context.Context) []*UnitCategory {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UnitCategory IDs.
func (_q *UnitCategoryQuery) IDs(ctx context.Context) (ids []uint32, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(unitcategory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *UnitCategoryQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *UnitCategoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*UnitCategoryQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *UnitCategoryQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *UnitCategoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *UnitCategoryQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UnitCategoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *UnitCategoryQuery) Clone() *UnitCategoryQuery {
	if _q == nil {
		return nil
	}
	return &UnitCategoryQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]unitcategory.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.UnitCategory{}, _q.predicates...),
		withUnits:  _q.withUnits.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithUnits tells the query-builder to eager-load the nodes that are connected to
// the "units" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UnitCategoryQuery) WithUnits(opts ...func(*UnitQuery)) *UnitCategoryQuery {
	query := (&UnitClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUnits = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UnitCategory.Query().
//		GroupBy(unitcategory.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *UnitCategoryQuery) GroupBy(field string, fields ...string) *UnitCategoryGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UnitCategoryGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = unitcategory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.UnitCategory.Query().
//		Select(unitcategory.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *UnitCategoryQuery) Select(fields ...string) *UnitCategorySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &UnitCategorySelect{UnitCategoryQuery: _q}
	sbuild.label = unitcategory.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UnitCategorySelect configured with the given aggregations.
func (_q *UnitCategoryQuery) Aggregate(fns ...AggregateFunc) *UnitCategorySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *UnitCategoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !unitcategory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	if unitcategory.Policy == nil {
		return errors.New("ent: uninitialized unitcategory.Policy (forgotten import ent/runtime?)")
	}
	if err := unitcategory.Policy.EvalQuery(ctx, _q); err != nil {
		return err
	}
	return nil
}

func (_q *UnitCategoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UnitCategory, error) {
	var (
		nodes       = []*UnitCategory{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withUnits != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UnitCategory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UnitCategory{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUnits; query != nil {
		if err := _q.loadUnits(ctx, query, nodes,
			func(n *UnitCategory) { n.Edges.Units = []*Unit{} },
			func(n *UnitCategory, e *Unit) { n.Edges.Units = append(n.Edges.Units, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *UnitCategoryQuery) loadUnits(ctx context.Context, query *UnitQuery, nodes []*UnitCategory, init func(*UnitCategory), assign func(*UnitCategory, *Unit)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint32]*UnitCategory)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(unit.FieldCategoryID)
	}
	query.Where(predicate.Unit(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(unitcategory.UnitsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CategoryID
		if fk == nil {
			return fmt.Errorf(`foreign-key "category_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "category_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *UnitCategoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *UnitCategoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(unitcategory.Table, unitcategory.Columns, sqlgraph.NewFieldSpec(unitcategory.FieldID, field.TypeUint32))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, unitcategory.FieldID)
		for i := range fields {
			if fields[i] != unitcategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *UnitCategoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(unitcategory.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = unitcategory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *UnitCategoryQuery) ForUpdate(opts ...sql.LockOption) *UnitCategoryQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *UnitCategoryQuery) ForShare(opts ...sql.LockOption) *UnitCategoryQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *UnitCategoryQuery) Modify(modifiers ...func(s *sql.Selector)) *UnitCategorySelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// UnitCategoryGroupBy is the group-by builder for UnitCategory entities.
type UnitCategoryGroupBy struct {
	selector
	build *UnitCategoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *UnitCategoryGroupBy) Aggregate(fns ...AggregateFunc) *UnitCategoryGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *UnitCategoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UnitCategoryQuery, *UnitCategoryGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *UnitCategoryGroupBy) sqlScan(ctx context.Context, root *UnitCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UnitCategorySelect is the builder for selecting fields of UnitCategory entities.
type UnitCategorySelect struct {
	*UnitCategoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *UnitCategorySelect) Aggregate(fns ...AggregateFunc) *UnitCategorySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *UnitCategorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UnitCategoryQuery, *UnitCategorySelect](ctx, _s.UnitCategoryQuery, _s, _s.inters, v)
}

func (_s *UnitCategorySelect) sqlScan(ctx context.Context, root *UnitCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *UnitCategorySelect) Modify(modifiers ...func(s *sql.Selector)) *UnitCategorySelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
