// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/admin/service/internal/data/ent/unit"
	"go-wind-admin/app/admin/service/internal/data/ent/unitcategory"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UnitCreate is the builder for creating a Unit entity.
type UnitCreate struct {
	config
	mutation *UnitMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UnitCreate) SetCreatedAt(v time.Time) *UnitCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UnitCreate) SetNillableCreatedAt(v *time.Time) *UnitCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UnitCreate) SetUpdatedAt(v time.Time) *UnitCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UnitCreate) SetNillableUpdatedAt(v *time.Time) *UnitCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UnitCreate) SetDeletedAt(v time.Time) *UnitCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UnitCreate) SetNillableDeletedAt(v *time.Time) *UnitCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *UnitCreate) SetCreatedBy(v uint32) *UnitCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *UnitCreate) SetNillableCreatedBy(v *uint32) *UnitCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *UnitCreate) SetUpdatedBy(v uint32) *UnitCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *UnitCreate) SetNillableUpdatedBy(v *uint32) *UnitCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *UnitCreate) SetDeletedBy(v uint32) *UnitCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *UnitCreate) SetNillableDeletedBy(v *uint32) *UnitCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *UnitCreate) SetSortOrder(v uint32) *UnitCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *UnitCreate) SetNillableSortOrder(v *uint32) *UnitCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetIsEnabled sets the "is_enabled" field.
func (_c *UnitCreate) SetIsEnabled(v bool) *UnitCreate {
	_c.mutation.SetIsEnabled(v)
	return _c
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_c *UnitCreate) SetNillableIsEnabled(v *bool) *UnitCreate {
	if v != nil {
		_c.SetIsEnabled(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *UnitCreate) SetTenantID(v uint32) *UnitCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *UnitCreate) SetNillableTenantID(v *uint32) *UnitCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetCategoryID sets the "category_id" field.
func (_c *UnitCreate) SetCategoryID(v uint32) *UnitCreate {
	_c.mutation.SetCategoryID(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *UnitCreate) SetCode(v string) *UnitCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_c *UnitCreate) SetNillableCode(v *string) *UnitCreate {
	if v != nil {
		_c.SetCode(*v)
	}
	return _c
}

// SetSymbol sets the "symbol" field.
func (_c *UnitCreate) SetSymbol(v string) *UnitCreate {
	_c.mutation.SetSymbol(v)
	return _c
}

// SetNillableSymbol sets the "symbol" field if the given value is not nil.
func (_c *UnitCreate) SetNillableSymbol(v *string) *UnitCreate {
	if v != nil {
		_c.SetSymbol(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *UnitCreate) SetName(v string) *UnitCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *UnitCreate) SetNillableName(v *string) *UnitCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetNameEn sets the "name_en" field.
func (_c *UnitCreate) SetNameEn(v string) *UnitCreate {
	_c.mutation.SetNameEn(v)
	return _c
}

// SetNillableNameEn sets the "name_en" field if the given value is not nil.
func (_c *UnitCreate) SetNillableNameEn(v *string) *UnitCreate {
	if v != nil {
		_c.SetNameEn(*v)
	}
	return _c
}

// SetIsBase sets the "is_base" field.
func (_c *UnitCreate) SetIsBase(v bool) *UnitCreate {
	_c.mutation.SetIsBase(v)
	return _c
}

// SetNillableIsBase sets the "is_base" field if the given value is not nil.
func (_c *UnitCreate) SetNillableIsBase(v *bool) *UnitCreate {
	if v != nil {
		_c.SetIsBase(*v)
	}
	return _c
}

// SetConversionType sets the "conversion_type" field.
func (_c *UnitCreate) SetConversionType(v unit.ConversionType) *UnitCreate {
	_c.mutation.SetConversionType(v)
	return _c
}

// SetNillableConversionType sets the "conversion_type" field if the given value is not nil.
func (_c *UnitCreate) SetNillableConversionType(v *unit.ConversionType) *UnitCreate {
	if v != nil {
		_c.SetConversionType(*v)
	}
	return _c
}

// SetFactor sets the "factor" field.
func (_c *UnitCreate) SetFactor(v float64) *UnitCreate {
	_c.mutation.SetFactor(v)
	return _c
}

// SetNillableFactor sets the "factor" field if the given value is not nil.
func (_c *UnitCreate) SetNillableFactor(v *float64) *UnitCreate {
	if v != nil {
		_c.SetFactor(*v)
	}
	return _c
}

// SetOffset sets the "offset" field.
func (_c *UnitCreate) SetOffset(v float64) *UnitCreate {
	_c.mutation.SetOffset(v)
	return _c
}

// SetNillableOffset sets the "offset" field if the given value is not nil.
func (_c *UnitCreate) SetNillableOffset(v *float64) *UnitCreate {
	if v != nil {
		_c.SetOffset(*v)
	}
	return _c
}

// SetFormulaExpr sets the "formula_expr" field.
func (_c *UnitCreate) SetFormulaExpr(v string) *UnitCreate {
	_c.mutation.SetFormulaExpr(v)
	return _c
}

// SetNillableFormulaExpr sets the "formula_expr" field if the given value is not nil.
func (_c *UnitCreate) SetNillableFormulaExpr(v *string) *UnitCreate {
	if v != nil {
		_c.SetFormulaExpr(*v)
	}
	return _c
}

// SetPrecision sets the "precision" field.
func (_c *UnitCreate) SetPrecision(v int32) *UnitCreate {
	_c.mutation.SetPrecision(v)
	return _c
}

// SetNillablePrecision sets the "precision" field if the given value is not nil.
func (_c *UnitCreate) SetNillablePrecision(v *int32) *UnitCreate {
	if v != nil {
		_c.SetPrecision(*v)
	}
	return _c
}

// SetIsSiUnit sets the "is_si_unit" field.
func (_c *UnitCreate) SetIsSiUnit(v bool) *UnitCreate {
	_c.mutation.SetIsSiUnit(v)
	return _c
}

// SetNillableIsSiUnit sets the "is_si_unit" field if the given value is not nil.
func (_c *UnitCreate) SetNillableIsSiUnit(v *bool) *UnitCreate {
	if v != nil {
		_c.SetIsSiUnit(*v)
	}
	return _c
}

// SetIsLegalUnit sets the "is_legal_unit" field.
func (_c *UnitCreate) SetIsLegalUnit(v bool) *UnitCreate {
	_c.mutation.SetIsLegalUnit(v)
	return _c
}

// SetNillableIsLegalUnit sets the "is_legal_unit" field if the given value is not nil.
func (_c *UnitCreate) SetNillableIsLegalUnit(v *bool) *UnitCreate {
	if v != nil {
		_c.SetIsLegalUnit(*v)
	}
	return _c
}

// SetReferenceCount sets the "reference_count" field.
func (_c *UnitCreate) SetReferenceCount(v uint32) *UnitCreate {
	_c.mutation.SetReferenceCount(v)
	return _c
}

// SetNillableReferenceCount sets the "reference_count" field if the given value is not nil.
func (_c *UnitCreate) SetNillableReferenceCount(v *uint32) *UnitCreate {
	if v != nil {
		_c.SetReferenceCount(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UnitCreate) SetID(v uint32) *UnitCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetCategory sets the "category" edge to the UnitCategory entity.
func (_c *UnitCreate) SetCategory(v *UnitCategory) *UnitCreate {
	return _c.SetCategoryID(v.ID)
}

// Mutation returns the UnitMutation object of the builder.
func (_c *UnitCreate) Mutation() *UnitMutation {
	return _c.mutation
}

// Save creates the Unit in the database.
func (_c *UnitCreate) Save(ctx context.Context) (*Unit, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UnitCreate) SaveX(ctx context.Context) *Unit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UnitCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UnitCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UnitCreate) defaults() error {
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := unit.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.IsEnabled(); !ok {
		v := unit.DefaultIsEnabled
		_c.mutation.SetIsEnabled(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := unit.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.IsBase(); !ok {
		v := unit.DefaultIsBase
		_c.mutation.SetIsBase(v)
	}
	if _, ok := _c.mutation.ConversionType(); !ok {
		v := unit.DefaultConversionType
		_c.mutation.SetConversionType(v)
	}
	if _, ok := _c.mutation.Factor(); !ok {
		v := unit.DefaultFactor
		_c.mutation.SetFactor(v)
	}
	if _, ok := _c.mutation.Offset(); !ok {
		v := unit.DefaultOffset
		_c.mutation.SetOffset(v)
	}
	if _, ok := _c.mutation.Precision(); !ok {
		v := unit.DefaultPrecision
		_c.mutation.SetPrecision(v)
	}
	if _, ok := _c.mutation.IsSiUnit(); !ok {
		v := unit.DefaultIsSiUnit
		_c.mutation.SetIsSiUnit(v)
	}
	if _, ok := _c.mutation.IsLegalUnit(); !ok {
		v := unit.DefaultIsLegalUnit
		_c.mutation.SetIsLegalUnit(v)
	}
	if _, ok := _c.mutation.ReferenceCount(); !ok {
		v := unit.DefaultReferenceCount
		_c.mutation.SetReferenceCount(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UnitCreate) check() error {
	if _, ok := _c.mutation.CategoryID(); !ok {
		return &ValidationError{Name: "category_id", err: errors.New(`ent: missing required field "Unit.category_id"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := unit.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Unit.code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Symbol(); ok {
		if err := unit.SymbolValidator(v); err != nil {
			return &ValidationError{Name: "symbol", err: fmt.Errorf(`ent: validator failed for field "Unit.symbol": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := unit.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Unit.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsBase(); !ok {
		return &ValidationError{Name: "is_base", err: errors.New(`ent: missing required field "Unit.is_base"`)}
	}
	if v, ok := _c.mutation.ConversionType(); ok {
		if err := unit.ConversionTypeValidator(v); err != nil {
			return &ValidationError{Name: "conversion_type", err: fmt.Errorf(`ent: validator failed for field "Unit.conversion_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Factor(); !ok {
		return &ValidationError{Name: "factor", err: errors.New(`ent: missing required field "Unit.factor"`)}
	}
	if _, ok := _c.mutation.Offset(); !ok {
		return &ValidationError{Name: "offset", err: errors.New(`ent: missing required field "Unit.offset"`)}
	}
	if _, ok := _c.mutation.IsSiUnit(); !ok {
		return &ValidationError{Name: "is_si_unit", err: errors.New(`ent: missing required field "Unit.is_si_unit"`)}
	}
	if _, ok := _c.mutation.IsLegalUnit(); !ok {
		return &ValidationError{Name: "is_legal_unit", err: errors.New(`ent: missing required field "Unit.is_legal_unit"`)}
	}
	if _, ok := _c.mutation.ReferenceCount(); !ok {
		return &ValidationError{Name: "reference_count", err: errors.New(`ent: missing required field "Unit.reference_count"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := unit.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Unit.id": %w`, err)}
		}
	}
	if len(_c.mutation.CategoryIDs()) == 0 {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required edge "Unit.category"`)}
	}
	return nil
}

func (_c *UnitCreate) sqlSave(ctx context.Context) (*Unit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UnitCreate) createSpec() (*Unit, *sqlgraph.CreateSpec) {
	var (
		_node = &Unit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(unit.Table, sqlgraph.NewFieldSpec(unit.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(unit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(unit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(unit.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(unit.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(unit.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(unit.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(unit.FieldSortOrder, field.TypeUint32, value)
		_node.SortOrder = &value
	}
	if value, ok := _c.mutation.IsEnabled(); ok {
		_spec.SetField(unit.FieldIsEnabled, field.TypeBool, value)
		_node.IsEnabled = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(unit.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(unit.FieldCode, field.TypeString, value)
		_node.Code = &value
	}
	if value, ok := _c.mutation.Symbol(); ok {
		_spec.SetField(unit.FieldSymbol, field.TypeString, value)
		_node.Symbol = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(unit.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	if value, ok := _c.mutation.NameEn(); ok {
		_spec.SetField(unit.FieldNameEn, field.TypeString, value)
		_node.NameEn = &value
	}
	if value, ok := _c.mutation.IsBase(); ok {
		_spec.SetField(unit.FieldIsBase, field.TypeBool, value)
		_node.IsBase = &value
	}
	if value, ok := _c.mutation.ConversionType(); ok {
		_spec.SetField(unit.FieldConversionType, field.TypeEnum, value)
		_node.ConversionType = &value
	}
	if value, ok := _c.mutation.Factor(); ok {
		_spec.SetField(unit.FieldFactor, field.TypeFloat64, value)
		_node.Factor = &value
	}
	if value, ok := _c.mutation.Offset(); ok {
		_spec.SetField(unit.FieldOffset, field.TypeFloat64, value)
		_node.Offset = &value
	}
	if value, ok := _c.mutation.FormulaExpr(); ok {
		_spec.SetField(unit.FieldFormulaExpr, field.TypeString, value)
		_node.FormulaExpr = &value
	}
	if value, ok := _c.mutation.Precision(); ok {
		_spec.SetField(unit.FieldPrecision, field.TypeInt32, value)
		_node.Precision = &value
	}
	if value, ok := _c.mutation.IsSiUnit(); ok {
		_spec.SetField(unit.FieldIsSiUnit, field.TypeBool, value)
		_node.IsSiUnit = &value
	}
	if value, ok := _c.mutation.IsLegalUnit(); ok {
		_spec.SetField(unit.FieldIsLegalUnit, field.TypeBool, value)
		_node.IsLegalUnit = &value
	}
	if value, ok := _c.mutation.ReferenceCount(); ok {
		_spec.SetField(unit.FieldReferenceCount, field.TypeUint32, value)
		_node.ReferenceCount = &value
	}
	if nodes := _c.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   unit.CategoryTable,
			Columns: []string{unit.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unitcategory.FieldID, field.TypeUint32),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CategoryID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Unit.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UnitUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UnitCreate) OnConflict(opts ...sql.ConflictOption) *UnitUpsertOne {
	_c.conflict = opts
	return &UnitUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Unit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UnitCreate) OnConflictColumns(columns ...string) *UnitUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UnitUpsertOne{
		create: _c,
	}
}

type (
	// UnitUpsertOne is the builder for "upsert"-ing
	//  one Unit node.
	UnitUpsertOne struct {
		create *UnitCreate
	}

	// UnitUpsert is the "OnConflict" setter.
	UnitUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UnitUpsert) SetUpdatedAt(v time.Time) *UnitUpsert {
	u.Set(unit.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UnitUpsert) UpdateUpdatedAt() *UnitUpsert {
	u.SetExcluded(unit.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *UnitUpsert) ClearUpdatedAt() *UnitUpsert {
	u.SetNull(unit.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UnitUpsert) SetDeletedAt(v time.Time) *UnitUpsert {
	u.Set(unit.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UnitUpsert) UpdateDeletedAt() *UnitUpsert {
	u.SetExcluded(unit.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UnitUpsert) ClearDeletedAt() *UnitUpsert {
	u.SetNull(unit.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *UnitUpsert) SetCreatedBy(v uint32) *UnitUpsert {
	u.Set(unit.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *UnitUpsert) UpdateCreatedBy() *UnitUpsert {
	u.SetExcluded(unit.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *UnitUpsert) AddCreatedBy(v uint32) *UnitUpsert {
	u.Add(unit.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *UnitUpsert) ClearCreatedBy() *UnitUpsert {
	u.SetNull(unit.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *UnitUpsert) SetUpdatedBy(v uint32) *UnitUpsert {
	u.Set(unit.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *UnitUpsert) UpdateUpdatedBy() *UnitUpsert {
	u.SetExcluded(unit.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *UnitUpsert) AddUpdatedBy(v uint32) *UnitUpsert {
	u.Add(unit.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *UnitUpsert) ClearUpdatedBy() *UnitUpsert {
	u.SetNull(unit.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *UnitUpsert) SetDeletedBy(v uint32) *UnitUpsert {
	u.Set(unit.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *UnitUpsert) UpdateDeletedBy() *UnitUpsert {
	u.SetExcluded(unit.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *UnitUpsert) AddDeletedBy(v uint32) *UnitUpsert {
	u.Add(unit.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *UnitUpsert) ClearDeletedBy() *UnitUpsert {
	u.SetNull(unit.FieldDeletedBy)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *UnitUpsert) SetSortOrder(v uint32) *UnitUpsert {
	u.Set(unit.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *UnitUpsert) UpdateSortOrder() *UnitUpsert {
	u.SetExcluded(unit.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *UnitUpsert) AddSortOrder(v uint32) *UnitUpsert {
	u.Add(unit.FieldSortOrder, v)
	return u
}

// ClearSortOrder clears the value of the "sort_order" field.
func (u *UnitUpsert) ClearSortOrder() *UnitUpsert {
	u.SetNull(unit.FieldSortOrder)
	return u
}

// SetIsEnabled sets the "is_enabled" field.
func (u *UnitUpsert) SetIsEnabled(v bool) *UnitUpsert {
	u.Set(unit.FieldIsEnabled, v)
	return u
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *UnitUpsert) UpdateIsEnabled() *UnitUpsert {
	u.SetExcluded(unit.FieldIsEnabled)
	return u
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (u *UnitUpsert) ClearIsEnabled() *UnitUpsert {
	u.SetNull(unit.FieldIsEnabled)
	return u
}

// SetCategoryID sets the "category_id" field.
func (u *UnitUpsert) SetCategoryID(v uint32) *UnitUpsert {
	u.Set(unit.FieldCategoryID, v)
	return u
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *UnitUpsert) UpdateCategoryID() *UnitUpsert {
	u.SetExcluded(unit.FieldCategoryID)
	return u
}

// SetSymbol sets the "symbol" field.
func (u *UnitUpsert) SetSymbol(v string) *UnitUpsert {
	u.Set(unit.FieldSymbol, v)
	return u
}

// UpdateSymbol sets the "symbol" field to the value that was provided on create.
func (u *UnitUpsert) UpdateSymbol() *UnitUpsert {
	u.SetExcluded(unit.FieldSymbol)
	return u
}

// ClearSymbol clears the value of the "symbol" field.
func (u *UnitUpsert) ClearSymbol() *UnitUpsert {
	u.SetNull(unit.FieldSymbol)
	return u
}

// SetName sets the "name" field.
func (u *UnitUpsert) SetName(v string) *UnitUpsert {
	u.Set(unit.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UnitUpsert) UpdateName() *UnitUpsert {
	u.SetExcluded(unit.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *UnitUpsert) ClearName() *UnitUpsert {
	u.SetNull(unit.FieldName)
	return u
}

// SetNameEn sets the "name_en" field.
func (u *UnitUpsert) SetNameEn(v string) *UnitUpsert {
	u.Set(unit.FieldNameEn, v)
	return u
}

// UpdateNameEn sets the "name_en" field to the value that was provided on create.
func (u *UnitUpsert) UpdateNameEn() *UnitUpsert {
	u.SetExcluded(unit.FieldNameEn)
	return u
}

// ClearNameEn clears the value of the "name_en" field.
func (u *UnitUpsert) ClearNameEn() *UnitUpsert {
	u.SetNull(unit.FieldNameEn)
	return u
}

// SetIsBase sets the "is_base" field.
func (u *UnitUpsert) SetIsBase(v bool) *UnitUpsert {
	u.Set(unit.FieldIsBase, v)
	return u
}

// UpdateIsBase sets the "is_base" field to the value that was provided on create.
func (u *UnitUpsert) UpdateIsBase() *UnitUpsert {
	u.SetExcluded(unit.FieldIsBase)
	return u
}

// SetConversionType sets the "conversion_type" field.
func (u *UnitUpsert) SetConversionType(v unit.ConversionType) *UnitUpsert {
	u.Set(unit.FieldConversionType, v)
	return u
}

// UpdateConversionType sets the "conversion_type" field to the value that was provided on create.
func (u *UnitUpsert) UpdateConversionType() *UnitUpsert {
	u.SetExcluded(unit.FieldConversionType)
	return u
}

// ClearConversionType clears the value of the "conversion_type" field.
func (u *UnitUpsert) ClearConversionType() *UnitUpsert {
	u.SetNull(unit.FieldConversionType)
	return u
}

// SetFactor sets the "factor" field.
func (u *UnitUpsert) SetFactor(v float64) *UnitUpsert {
	u.Set(unit.FieldFactor, v)
	return u
}

// UpdateFactor sets the "factor" field to the value that was provided on create.
func (u *UnitUpsert) UpdateFactor() *UnitUpsert {
	u.SetExcluded(unit.FieldFactor)
	return u
}

// AddFactor adds v to the "factor" field.
func (u *UnitUpsert) AddFactor(v float64) *UnitUpsert {
	u.Add(unit.FieldFactor, v)
	return u
}

// SetOffset sets the "offset" field.
func (u *UnitUpsert) SetOffset(v float64) *UnitUpsert {
	u.Set(unit.FieldOffset, v)
	return u
}

// UpdateOffset sets the "offset" field to the value that was provided on create.
func (u *UnitUpsert) UpdateOffset() *UnitUpsert {
	u.SetExcluded(unit.FieldOffset)
	return u
}

// AddOffset adds v to the "offset" field.
func (u *UnitUpsert) AddOffset(v float64) *UnitUpsert {
	u.Add(unit.FieldOffset, v)
	return u
}

// SetFormulaExpr sets the "formula_expr" field.
func (u *UnitUpsert) SetFormulaExpr(v string) *UnitUpsert {
	u.Set(unit.FieldFormulaExpr, v)
	return u
}

// UpdateFormulaExpr sets the "formula_expr" field to the value that was provided on create.
func (u *UnitUpsert) UpdateFormulaExpr() *UnitUpsert {
	u.SetExcluded(unit.FieldFormulaExpr)
	return u
}

// ClearFormulaExpr clears the value of the "formula_expr" field.
func (u *UnitUpsert) ClearFormulaExpr() *UnitUpsert {
	u.SetNull(unit.FieldFormulaExpr)
	return u
}

// SetPrecision sets the "precision" field.
func (u *UnitUpsert) SetPrecision(v int32) *UnitUpsert {
	u.Set(unit.FieldPrecision, v)
	return u
}

// UpdatePrecision sets the "precision" field to the value that was provided on create.
func (u *UnitUpsert) UpdatePrecision() *UnitUpsert {
	u.SetExcluded(unit.FieldPrecision)
	return u
}

// AddPrecision adds v to the "precision" field.
func (u *UnitUpsert) AddPrecision(v int32) *UnitUpsert {
	u.Add(unit.FieldPrecision, v)
	return u
}

// ClearPrecision clears the value of the "precision" field.
func (u *UnitUpsert) ClearPrecision() *UnitUpsert {
	u.SetNull(unit.FieldPrecision)
	return u
}

// SetIsSiUnit sets the "is_si_unit" field.
func (u *UnitUpsert) SetIsSiUnit(v bool) *UnitUpsert {
	u.Set(unit.FieldIsSiUnit, v)
	return u
}

// UpdateIsSiUnit sets the "is_si_unit" field to the value that was provided on create.
func (u *UnitUpsert) UpdateIsSiUnit() *UnitUpsert {
	u.SetExcluded(unit.FieldIsSiUnit)
	return u
}

// SetIsLegalUnit sets the "is_legal_unit" field.
func (u *UnitUpsert) SetIsLegalUnit(v bool) *UnitUpsert {
	u.Set(unit.FieldIsLegalUnit, v)
	return u
}

// UpdateIsLegalUnit sets the "is_legal_unit" field to the value that was provided on create.
func (u *UnitUpsert) UpdateIsLegalUnit() *UnitUpsert {
	u.SetExcluded(unit.FieldIsLegalUnit)
	return u
}

// SetReferenceCount sets the "reference_count" field.
func (u *UnitUpsert) SetReferenceCount(v uint32) *UnitUpsert {
	u.Set(unit.FieldReferenceCount, v)
	return u
}

// UpdateReferenceCount sets the "reference_count" field to the value that was provided on create.
func (u *UnitUpsert) UpdateReferenceCount() *UnitUpsert {
	u.SetExcluded(unit.FieldReferenceCount)
	return u
}

// AddReferenceCount adds v to the "reference_count" field.
func (u *UnitUpsert) AddReferenceCount(v uint32) *UnitUpsert {
	u.Add(unit.FieldReferenceCount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Unit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(unit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UnitUpsertOne) UpdateNewValues() *UnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(unit.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(unit.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(unit.FieldTenantID)
		}
		if _, exists := u.create.mutation.Code(); exists {
			s.SetIgnore(unit.FieldCode)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Unit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UnitUpsertOne) Ignore() *UnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UnitUpsertOne) DoNothing() *UnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UnitCreate.OnConflict
// documentation for more info.
func (u *UnitUpsertOne) Update(set func(*UnitUpsert)) *UnitUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UnitUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UnitUpsertOne) SetUpdatedAt(v time.Time) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateUpdatedAt() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *UnitUpsertOne) ClearUpdatedAt() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UnitUpsertOne) SetDeletedAt(v time.Time) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateDeletedAt() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UnitUpsertOne) ClearDeletedAt() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *UnitUpsertOne) SetCreatedBy(v uint32) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *UnitUpsertOne) AddCreatedBy(v uint32) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateCreatedBy() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *UnitUpsertOne) ClearCreatedBy() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *UnitUpsertOne) SetUpdatedBy(v uint32) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *UnitUpsertOne) AddUpdatedBy(v uint32) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateUpdatedBy() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *UnitUpsertOne) ClearUpdatedBy() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *UnitUpsertOne) SetDeletedBy(v uint32) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *UnitUpsertOne) AddDeletedBy(v uint32) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateDeletedBy() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *UnitUpsertOne) ClearDeletedBy() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.ClearDeletedBy()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *UnitUpsertOne) SetSortOrder(v uint32) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *UnitUpsertOne) AddSortOrder(v uint32) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateSortOrder() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateSortOrder()
	})
}

// ClearSortOrder clears the value of the "sort_order" field.
func (u *UnitUpsertOne) ClearSortOrder() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.ClearSortOrder()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *UnitUpsertOne) SetIsEnabled(v bool) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateIsEnabled() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateIsEnabled()
	})
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (u *UnitUpsertOne) ClearIsEnabled() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.ClearIsEnabled()
	})
}

// SetCategoryID sets the "category_id" field.
func (u *UnitUpsertOne) SetCategoryID(v uint32) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetCategoryID(v)
	})
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateCategoryID() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateCategoryID()
	})
}

// SetSymbol sets the "symbol" field.
func (u *UnitUpsertOne) SetSymbol(v string) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetSymbol(v)
	})
}

// UpdateSymbol sets the "symbol" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateSymbol() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateSymbol()
	})
}

// ClearSymbol clears the value of the "symbol" field.
func (u *UnitUpsertOne) ClearSymbol() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.ClearSymbol()
	})
}

// SetName sets the "name" field.
func (u *UnitUpsertOne) SetName(v string) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateName() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *UnitUpsertOne) ClearName() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.ClearName()
	})
}

// SetNameEn sets the "name_en" field.
func (u *UnitUpsertOne) SetNameEn(v string) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetNameEn(v)
	})
}

// UpdateNameEn sets the "name_en" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateNameEn() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateNameEn()
	})
}

// ClearNameEn clears the value of the "name_en" field.
func (u *UnitUpsertOne) ClearNameEn() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.ClearNameEn()
	})
}

// SetIsBase sets the "is_base" field.
func (u *UnitUpsertOne) SetIsBase(v bool) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetIsBase(v)
	})
}

// UpdateIsBase sets the "is_base" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateIsBase() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateIsBase()
	})
}

// SetConversionType sets the "conversion_type" field.
func (u *UnitUpsertOne) SetConversionType(v unit.ConversionType) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetConversionType(v)
	})
}

// UpdateConversionType sets the "conversion_type" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateConversionType() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateConversionType()
	})
}

// ClearConversionType clears the value of the "conversion_type" field.
func (u *UnitUpsertOne) ClearConversionType() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.ClearConversionType()
	})
}

// SetFactor sets the "factor" field.
func (u *UnitUpsertOne) SetFactor(v float64) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetFactor(v)
	})
}

// AddFactor adds v to the "factor" field.
func (u *UnitUpsertOne) AddFactor(v float64) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.AddFactor(v)
	})
}

// UpdateFactor sets the "factor" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateFactor() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateFactor()
	})
}

// SetOffset sets the "offset" field.
func (u *UnitUpsertOne) SetOffset(v float64) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetOffset(v)
	})
}

// AddOffset adds v to the "offset" field.
func (u *UnitUpsertOne) AddOffset(v float64) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.AddOffset(v)
	})
}

// UpdateOffset sets the "offset" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateOffset() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateOffset()
	})
}

// SetFormulaExpr sets the "formula_expr" field.
func (u *UnitUpsertOne) SetFormulaExpr(v string) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetFormulaExpr(v)
	})
}

// UpdateFormulaExpr sets the "formula_expr" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateFormulaExpr() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateFormulaExpr()
	})
}

// ClearFormulaExpr clears the value of the "formula_expr" field.
func (u *UnitUpsertOne) ClearFormulaExpr() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.ClearFormulaExpr()
	})
}

// SetPrecision sets the "precision" field.
func (u *UnitUpsertOne) SetPrecision(v int32) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetPrecision(v)
	})
}

// AddPrecision adds v to the "precision" field.
func (u *UnitUpsertOne) AddPrecision(v int32) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.AddPrecision(v)
	})
}

// UpdatePrecision sets the "precision" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdatePrecision() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdatePrecision()
	})
}

// ClearPrecision clears the value of the "precision" field.
func (u *UnitUpsertOne) ClearPrecision() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.ClearPrecision()
	})
}

// SetIsSiUnit sets the "is_si_unit" field.
func (u *UnitUpsertOne) SetIsSiUnit(v bool) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetIsSiUnit(v)
	})
}

// UpdateIsSiUnit sets the "is_si_unit" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateIsSiUnit() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateIsSiUnit()
	})
}

// SetIsLegalUnit sets the "is_legal_unit" field.
func (u *UnitUpsertOne) SetIsLegalUnit(v bool) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetIsLegalUnit(v)
	})
}

// UpdateIsLegalUnit sets the "is_legal_unit" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateIsLegalUnit() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateIsLegalUnit()
	})
}

// SetReferenceCount sets the "reference_count" field.
func (u *UnitUpsertOne) SetReferenceCount(v uint32) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.SetReferenceCount(v)
	})
}

// AddReferenceCount adds v to the "reference_count" field.
func (u *UnitUpsertOne) AddReferenceCount(v uint32) *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.AddReferenceCount(v)
	})
}

// UpdateReferenceCount sets the "reference_count" field to the value that was provided on create.
func (u *UnitUpsertOne) UpdateReferenceCount() *UnitUpsertOne {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateReferenceCount()
	})
}

// Exec executes the query.
func (u *UnitUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UnitCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UnitUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UnitUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UnitUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UnitCreateBulk is the builder for creating many Unit entities in bulk.
type UnitCreateBulk struct {
	config
	err      error
	builders []*UnitCreate
	conflict []sql.ConflictOption
}

// Save creates the Unit entities in the database.
func (_c *UnitCreateBulk) Save(ctx context.Context) ([]*Unit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Unit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UnitMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UnitCreateBulk) SaveX(ctx context.Context) []*Unit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UnitCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UnitCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Unit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UnitUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UnitCreateBulk) OnConflict(opts ...sql.ConflictOption) *UnitUpsertBulk {
	_c.conflict = opts
	return &UnitUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Unit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UnitCreateBulk) OnConflictColumns(columns ...string) *UnitUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UnitUpsertBulk{
		create: _c,
	}
}

// UnitUpsertBulk is the builder for "upsert"-ing
// a bulk of Unit nodes.
type UnitUpsertBulk struct {
	create *UnitCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Unit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(unit.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UnitUpsertBulk) UpdateNewValues() *UnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(unit.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(unit.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(unit.FieldTenantID)
			}
			if _, exists := b.mutation.Code(); exists {
				s.SetIgnore(unit.FieldCode)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Unit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UnitUpsertBulk) Ignore() *UnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UnitUpsertBulk) DoNothing() *UnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UnitCreateBulk.OnConflict
// documentation for more info.
func (u *UnitUpsertBulk) Update(set func(*UnitUpsert)) *UnitUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UnitUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UnitUpsertBulk) SetUpdatedAt(v time.Time) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateUpdatedAt() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *UnitUpsertBulk) ClearUpdatedAt() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UnitUpsertBulk) SetDeletedAt(v time.Time) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateDeletedAt() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UnitUpsertBulk) ClearDeletedAt() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *UnitUpsertBulk) SetCreatedBy(v uint32) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *UnitUpsertBulk) AddCreatedBy(v uint32) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateCreatedBy() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *UnitUpsertBulk) ClearCreatedBy() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *UnitUpsertBulk) SetUpdatedBy(v uint32) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *UnitUpsertBulk) AddUpdatedBy(v uint32) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateUpdatedBy() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *UnitUpsertBulk) ClearUpdatedBy() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *UnitUpsertBulk) SetDeletedBy(v uint32) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *UnitUpsertBulk) AddDeletedBy(v uint32) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateDeletedBy() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *UnitUpsertBulk) ClearDeletedBy() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.ClearDeletedBy()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *UnitUpsertBulk) SetSortOrder(v uint32) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *UnitUpsertBulk) AddSortOrder(v uint32) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateSortOrder() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateSortOrder()
	})
}

// ClearSortOrder clears the value of the "sort_order" field.
func (u *UnitUpsertBulk) ClearSortOrder() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.ClearSortOrder()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *UnitUpsertBulk) SetIsEnabled(v bool) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateIsEnabled() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateIsEnabled()
	})
}

// ClearIsEnabled clears the value of the "is_enabled" field.
func (u *UnitUpsertBulk) ClearIsEnabled() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.ClearIsEnabled()
	})
}

// SetCategoryID sets the "category_id" field.
func (u *UnitUpsertBulk) SetCategoryID(v uint32) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetCategoryID(v)
	})
}

// UpdateCategoryID sets the "category_id" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateCategoryID() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateCategoryID()
	})
}

// SetSymbol sets the "symbol" field.
func (u *UnitUpsertBulk) SetSymbol(v string) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetSymbol(v)
	})
}

// UpdateSymbol sets the "symbol" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateSymbol() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateSymbol()
	})
}

// ClearSymbol clears the value of the "symbol" field.
func (u *UnitUpsertBulk) ClearSymbol() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.ClearSymbol()
	})
}

// SetName sets the "name" field.
func (u *UnitUpsertBulk) SetName(v string) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateName() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *UnitUpsertBulk) ClearName() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.ClearName()
	})
}

// SetNameEn sets the "name_en" field.
func (u *UnitUpsertBulk) SetNameEn(v string) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetNameEn(v)
	})
}

// UpdateNameEn sets the "name_en" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateNameEn() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateNameEn()
	})
}

// ClearNameEn clears the value of the "name_en" field.
func (u *UnitUpsertBulk) ClearNameEn() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.ClearNameEn()
	})
}

// SetIsBase sets the "is_base" field.
func (u *UnitUpsertBulk) SetIsBase(v bool) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetIsBase(v)
	})
}

// UpdateIsBase sets the "is_base" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateIsBase() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateIsBase()
	})
}

// SetConversionType sets the "conversion_type" field.
func (u *UnitUpsertBulk) SetConversionType(v unit.ConversionType) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetConversionType(v)
	})
}

// UpdateConversionType sets the "conversion_type" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateConversionType() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateConversionType()
	})
}

// ClearConversionType clears the value of the "conversion_type" field.
func (u *UnitUpsertBulk) ClearConversionType() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.ClearConversionType()
	})
}

// SetFactor sets the "factor" field.
func (u *UnitUpsertBulk) SetFactor(v float64) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetFactor(v)
	})
}

// AddFactor adds v to the "factor" field.
func (u *UnitUpsertBulk) AddFactor(v float64) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.AddFactor(v)
	})
}

// UpdateFactor sets the "factor" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateFactor() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateFactor()
	})
}

// SetOffset sets the "offset" field.
func (u *UnitUpsertBulk) SetOffset(v float64) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetOffset(v)
	})
}

// AddOffset adds v to the "offset" field.
func (u *UnitUpsertBulk) AddOffset(v float64) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.AddOffset(v)
	})
}

// UpdateOffset sets the "offset" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateOffset() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateOffset()
	})
}

// SetFormulaExpr sets the "formula_expr" field.
func (u *UnitUpsertBulk) SetFormulaExpr(v string) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetFormulaExpr(v)
	})
}

// UpdateFormulaExpr sets the "formula_expr" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateFormulaExpr() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateFormulaExpr()
	})
}

// ClearFormulaExpr clears the value of the "formula_expr" field.
func (u *UnitUpsertBulk) ClearFormulaExpr() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.ClearFormulaExpr()
	})
}

// SetPrecision sets the "precision" field.
func (u *UnitUpsertBulk) SetPrecision(v int32) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetPrecision(v)
	})
}

// AddPrecision adds v to the "precision" field.
func (u *UnitUpsertBulk) AddPrecision(v int32) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.AddPrecision(v)
	})
}

// UpdatePrecision sets the "precision" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdatePrecision() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdatePrecision()
	})
}

// ClearPrecision clears the value of the "precision" field.
func (u *UnitUpsertBulk) ClearPrecision() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.ClearPrecision()
	})
}

// SetIsSiUnit sets the "is_si_unit" field.
func (u *UnitUpsertBulk) SetIsSiUnit(v bool) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetIsSiUnit(v)
	})
}

// UpdateIsSiUnit sets the "is_si_unit" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateIsSiUnit() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateIsSiUnit()
	})
}

// SetIsLegalUnit sets the "is_legal_unit" field.
func (u *UnitUpsertBulk) SetIsLegalUnit(v bool) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetIsLegalUnit(v)
	})
}

// UpdateIsLegalUnit sets the "is_legal_unit" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateIsLegalUnit() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateIsLegalUnit()
	})
}

// SetReferenceCount sets the "reference_count" field.
func (u *UnitUpsertBulk) SetReferenceCount(v uint32) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.SetReferenceCount(v)
	})
}

// AddReferenceCount adds v to the "reference_count" field.
func (u *UnitUpsertBulk) AddReferenceCount(v uint32) *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.AddReferenceCount(v)
	})
}

// UpdateReferenceCount sets the "reference_count" field to the value that was provided on create.
func (u *UnitUpsertBulk) UpdateReferenceCount() *UnitUpsertBulk {
	return u.Update(func(s *UnitUpsert) {
		s.UpdateReferenceCount()
	})
}

// Exec executes the query.
func (u *UnitUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UnitCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UnitCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UnitUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
