// Code generated by ent, DO NOT EDIT.

package feature

import (
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldDeletedBy, v))
}

// IsEnabled applies equality check predicate on the "is_enabled" field. It's identical to IsEnabledEQ.
func IsEnabled(v bool) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldIsEnabled, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldSortOrder, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldTenantID, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldCode, v))
}

// Identifier applies equality check predicate on the "identifier" field. It's identical to IdentifierEQ.
func Identifier(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldIdentifier, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldName, v))
}

// NameEn applies equality check predicate on the "name_en" field. It's identical to NameEnEQ.
func NameEn(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldNameEn, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldDescription, v))
}

// ApplicableScope applies equality check predicate on the "applicable_scope" field. It's identical to ApplicableScopeEQ.
func ApplicableScope(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldApplicableScope, v))
}

// RelationType applies equality check predicate on the "relation_type" field. It's identical to RelationTypeEQ.
func RelationType(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldRelationType, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldDeletedBy))
}

// IsEnabledEQ applies the EQ predicate on the "is_enabled" field.
func IsEnabledEQ(v bool) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldIsEnabled, v))
}

// IsEnabledNEQ applies the NEQ predicate on the "is_enabled" field.
func IsEnabledNEQ(v bool) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldIsEnabled, v))
}

// IsEnabledIsNil applies the IsNil predicate on the "is_enabled" field.
func IsEnabledIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldIsEnabled))
}

// IsEnabledNotNil applies the NotNil predicate on the "is_enabled" field.
func IsEnabledNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldIsEnabled))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...uint32) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...uint32) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldSortOrder, v))
}

// SortOrderIsNil applies the IsNil predicate on the "sort_order" field.
func SortOrderIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldSortOrder))
}

// SortOrderNotNil applies the NotNil predicate on the "sort_order" field.
func SortOrderNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldSortOrder))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldTenantID))
}

// FeatureTypeEQ applies the EQ predicate on the "feature_type" field.
func FeatureTypeEQ(v FeatureType) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldFeatureType, v))
}

// FeatureTypeNEQ applies the NEQ predicate on the "feature_type" field.
func FeatureTypeNEQ(v FeatureType) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldFeatureType, v))
}

// FeatureTypeIn applies the In predicate on the "feature_type" field.
func FeatureTypeIn(vs ...FeatureType) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldFeatureType, vs...))
}

// FeatureTypeNotIn applies the NotIn predicate on the "feature_type" field.
func FeatureTypeNotIn(vs ...FeatureType) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldFeatureType, vs...))
}

// FeatureTypeIsNil applies the IsNil predicate on the "feature_type" field.
func FeatureTypeIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldFeatureType))
}

// FeatureTypeNotNil applies the NotNil predicate on the "feature_type" field.
func FeatureTypeNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldFeatureType))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldCode, v))
}

// CodeIsNil applies the IsNil predicate on the "code" field.
func CodeIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldCode))
}

// CodeNotNil applies the NotNil predicate on the "code" field.
func CodeNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldCode))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldCode, v))
}

// IdentifierEQ applies the EQ predicate on the "identifier" field.
func IdentifierEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldIdentifier, v))
}

// IdentifierNEQ applies the NEQ predicate on the "identifier" field.
func IdentifierNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldIdentifier, v))
}

// IdentifierIn applies the In predicate on the "identifier" field.
func IdentifierIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldIdentifier, vs...))
}

// IdentifierNotIn applies the NotIn predicate on the "identifier" field.
func IdentifierNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldIdentifier, vs...))
}

// IdentifierGT applies the GT predicate on the "identifier" field.
func IdentifierGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldIdentifier, v))
}

// IdentifierGTE applies the GTE predicate on the "identifier" field.
func IdentifierGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldIdentifier, v))
}

// IdentifierLT applies the LT predicate on the "identifier" field.
func IdentifierLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldIdentifier, v))
}

// IdentifierLTE applies the LTE predicate on the "identifier" field.
func IdentifierLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldIdentifier, v))
}

// IdentifierContains applies the Contains predicate on the "identifier" field.
func IdentifierContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldIdentifier, v))
}

// IdentifierHasPrefix applies the HasPrefix predicate on the "identifier" field.
func IdentifierHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldIdentifier, v))
}

// IdentifierHasSuffix applies the HasSuffix predicate on the "identifier" field.
func IdentifierHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldIdentifier, v))
}

// IdentifierIsNil applies the IsNil predicate on the "identifier" field.
func IdentifierIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldIdentifier))
}

// IdentifierNotNil applies the NotNil predicate on the "identifier" field.
func IdentifierNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldIdentifier))
}

// IdentifierEqualFold applies the EqualFold predicate on the "identifier" field.
func IdentifierEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldIdentifier, v))
}

// IdentifierContainsFold applies the ContainsFold predicate on the "identifier" field.
func IdentifierContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldIdentifier, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldName, v))
}

// NameEnEQ applies the EQ predicate on the "name_en" field.
func NameEnEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldNameEn, v))
}

// NameEnNEQ applies the NEQ predicate on the "name_en" field.
func NameEnNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldNameEn, v))
}

// NameEnIn applies the In predicate on the "name_en" field.
func NameEnIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldNameEn, vs...))
}

// NameEnNotIn applies the NotIn predicate on the "name_en" field.
func NameEnNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldNameEn, vs...))
}

// NameEnGT applies the GT predicate on the "name_en" field.
func NameEnGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldNameEn, v))
}

// NameEnGTE applies the GTE predicate on the "name_en" field.
func NameEnGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldNameEn, v))
}

// NameEnLT applies the LT predicate on the "name_en" field.
func NameEnLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldNameEn, v))
}

// NameEnLTE applies the LTE predicate on the "name_en" field.
func NameEnLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldNameEn, v))
}

// NameEnContains applies the Contains predicate on the "name_en" field.
func NameEnContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldNameEn, v))
}

// NameEnHasPrefix applies the HasPrefix predicate on the "name_en" field.
func NameEnHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldNameEn, v))
}

// NameEnHasSuffix applies the HasSuffix predicate on the "name_en" field.
func NameEnHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldNameEn, v))
}

// NameEnIsNil applies the IsNil predicate on the "name_en" field.
func NameEnIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldNameEn))
}

// NameEnNotNil applies the NotNil predicate on the "name_en" field.
func NameEnNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldNameEn))
}

// NameEnEqualFold applies the EqualFold predicate on the "name_en" field.
func NameEnEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldNameEn, v))
}

// NameEnContainsFold applies the ContainsFold predicate on the "name_en" field.
func NameEnContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldNameEn, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldDescription, v))
}

// ApplicableScopeEQ applies the EQ predicate on the "applicable_scope" field.
func ApplicableScopeEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldApplicableScope, v))
}

// ApplicableScopeNEQ applies the NEQ predicate on the "applicable_scope" field.
func ApplicableScopeNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldApplicableScope, v))
}

// ApplicableScopeIn applies the In predicate on the "applicable_scope" field.
func ApplicableScopeIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldApplicableScope, vs...))
}

// ApplicableScopeNotIn applies the NotIn predicate on the "applicable_scope" field.
func ApplicableScopeNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldApplicableScope, vs...))
}

// ApplicableScopeGT applies the GT predicate on the "applicable_scope" field.
func ApplicableScopeGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldApplicableScope, v))
}

// ApplicableScopeGTE applies the GTE predicate on the "applicable_scope" field.
func ApplicableScopeGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldApplicableScope, v))
}

// ApplicableScopeLT applies the LT predicate on the "applicable_scope" field.
func ApplicableScopeLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldApplicableScope, v))
}

// ApplicableScopeLTE applies the LTE predicate on the "applicable_scope" field.
func ApplicableScopeLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldApplicableScope, v))
}

// ApplicableScopeContains applies the Contains predicate on the "applicable_scope" field.
func ApplicableScopeContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldApplicableScope, v))
}

// ApplicableScopeHasPrefix applies the HasPrefix predicate on the "applicable_scope" field.
func ApplicableScopeHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldApplicableScope, v))
}

// ApplicableScopeHasSuffix applies the HasSuffix predicate on the "applicable_scope" field.
func ApplicableScopeHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldApplicableScope, v))
}

// ApplicableScopeIsNil applies the IsNil predicate on the "applicable_scope" field.
func ApplicableScopeIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldApplicableScope))
}

// ApplicableScopeNotNil applies the NotNil predicate on the "applicable_scope" field.
func ApplicableScopeNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldApplicableScope))
}

// ApplicableScopeEqualFold applies the EqualFold predicate on the "applicable_scope" field.
func ApplicableScopeEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldApplicableScope, v))
}

// ApplicableScopeContainsFold applies the ContainsFold predicate on the "applicable_scope" field.
func ApplicableScopeContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldApplicableScope, v))
}

// DataTypeEQ applies the EQ predicate on the "data_type" field.
func DataTypeEQ(v DataType) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldDataType, v))
}

// DataTypeNEQ applies the NEQ predicate on the "data_type" field.
func DataTypeNEQ(v DataType) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldDataType, v))
}

// DataTypeIn applies the In predicate on the "data_type" field.
func DataTypeIn(vs ...DataType) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldDataType, vs...))
}

// DataTypeNotIn applies the NotIn predicate on the "data_type" field.
func DataTypeNotIn(vs ...DataType) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldDataType, vs...))
}

// DataTypeIsNil applies the IsNil predicate on the "data_type" field.
func DataTypeIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldDataType))
}

// DataTypeNotNil applies the NotNil predicate on the "data_type" field.
func DataTypeNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldDataType))
}

// AccessModeEQ applies the EQ predicate on the "access_mode" field.
func AccessModeEQ(v AccessMode) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldAccessMode, v))
}

// AccessModeNEQ applies the NEQ predicate on the "access_mode" field.
func AccessModeNEQ(v AccessMode) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldAccessMode, v))
}

// AccessModeIn applies the In predicate on the "access_mode" field.
func AccessModeIn(vs ...AccessMode) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldAccessMode, vs...))
}

// AccessModeNotIn applies the NotIn predicate on the "access_mode" field.
func AccessModeNotIn(vs ...AccessMode) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldAccessMode, vs...))
}

// AccessModeIsNil applies the IsNil predicate on the "access_mode" field.
func AccessModeIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldAccessMode))
}

// AccessModeNotNil applies the NotNil predicate on the "access_mode" field.
func AccessModeNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldAccessMode))
}

// EventLevelEQ applies the EQ predicate on the "event_level" field.
func EventLevelEQ(v EventLevel) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldEventLevel, v))
}

// EventLevelNEQ applies the NEQ predicate on the "event_level" field.
func EventLevelNEQ(v EventLevel) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldEventLevel, v))
}

// EventLevelIn applies the In predicate on the "event_level" field.
func EventLevelIn(vs ...EventLevel) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldEventLevel, vs...))
}

// EventLevelNotIn applies the NotIn predicate on the "event_level" field.
func EventLevelNotIn(vs ...EventLevel) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldEventLevel, vs...))
}

// EventLevelIsNil applies the IsNil predicate on the "event_level" field.
func EventLevelIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldEventLevel))
}

// EventLevelNotNil applies the NotNil predicate on the "event_level" field.
func EventLevelNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldEventLevel))
}

// CallModeEQ applies the EQ predicate on the "call_mode" field.
func CallModeEQ(v CallMode) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldCallMode, v))
}

// CallModeNEQ applies the NEQ predicate on the "call_mode" field.
func CallModeNEQ(v CallMode) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldCallMode, v))
}

// CallModeIn applies the In predicate on the "call_mode" field.
func CallModeIn(vs ...CallMode) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldCallMode, vs...))
}

// CallModeNotIn applies the NotIn predicate on the "call_mode" field.
func CallModeNotIn(vs ...CallMode) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldCallMode, vs...))
}

// CallModeIsNil applies the IsNil predicate on the "call_mode" field.
func CallModeIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldCallMode))
}

// CallModeNotNil applies the NotNil predicate on the "call_mode" field.
func CallModeNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldCallMode))
}

// RelationTypeEQ applies the EQ predicate on the "relation_type" field.
func RelationTypeEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEQ(FieldRelationType, v))
}

// RelationTypeNEQ applies the NEQ predicate on the "relation_type" field.
func RelationTypeNEQ(v string) predicate.Feature {
	return predicate.Feature(sql.FieldNEQ(FieldRelationType, v))
}

// RelationTypeIn applies the In predicate on the "relation_type" field.
func RelationTypeIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldIn(FieldRelationType, vs...))
}

// RelationTypeNotIn applies the NotIn predicate on the "relation_type" field.
func RelationTypeNotIn(vs ...string) predicate.Feature {
	return predicate.Feature(sql.FieldNotIn(FieldRelationType, vs...))
}

// RelationTypeGT applies the GT predicate on the "relation_type" field.
func RelationTypeGT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGT(FieldRelationType, v))
}

// RelationTypeGTE applies the GTE predicate on the "relation_type" field.
func RelationTypeGTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldGTE(FieldRelationType, v))
}

// RelationTypeLT applies the LT predicate on the "relation_type" field.
func RelationTypeLT(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLT(FieldRelationType, v))
}

// RelationTypeLTE applies the LTE predicate on the "relation_type" field.
func RelationTypeLTE(v string) predicate.Feature {
	return predicate.Feature(sql.FieldLTE(FieldRelationType, v))
}

// RelationTypeContains applies the Contains predicate on the "relation_type" field.
func RelationTypeContains(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContains(FieldRelationType, v))
}

// RelationTypeHasPrefix applies the HasPrefix predicate on the "relation_type" field.
func RelationTypeHasPrefix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasPrefix(FieldRelationType, v))
}

// RelationTypeHasSuffix applies the HasSuffix predicate on the "relation_type" field.
func RelationTypeHasSuffix(v string) predicate.Feature {
	return predicate.Feature(sql.FieldHasSuffix(FieldRelationType, v))
}

// RelationTypeIsNil applies the IsNil predicate on the "relation_type" field.
func RelationTypeIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldRelationType))
}

// RelationTypeNotNil applies the NotNil predicate on the "relation_type" field.
func RelationTypeNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldRelationType))
}

// RelationTypeEqualFold applies the EqualFold predicate on the "relation_type" field.
func RelationTypeEqualFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldEqualFold(FieldRelationType, v))
}

// RelationTypeContainsFold applies the ContainsFold predicate on the "relation_type" field.
func RelationTypeContainsFold(v string) predicate.Feature {
	return predicate.Feature(sql.FieldContainsFold(FieldRelationType, v))
}

// SpecIsNil applies the IsNil predicate on the "spec" field.
func SpecIsNil() predicate.Feature {
	return predicate.Feature(sql.FieldIsNull(FieldSpec))
}

// SpecNotNil applies the NotNil predicate on the "spec" field.
func SpecNotNil() predicate.Feature {
	return predicate.Feature(sql.FieldNotNull(FieldSpec))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Feature) predicate.Feature {
	return predicate.Feature(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Feature) predicate.Feature {
	return predicate.Feature(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Feature) predicate.Feature {
	return predicate.Feature(sql.NotPredicates(p))
}
