// Code generated by ent, DO NOT EDIT.

package unit

import (
	"fmt"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the unit type in the database.
	Label = "unit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldIsEnabled holds the string denoting the is_enabled field in the database.
	FieldIsEnabled = "is_enabled"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldCategoryID holds the string denoting the category_id field in the database.
	FieldCategoryID = "category_id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldSymbol holds the string denoting the symbol field in the database.
	FieldSymbol = "symbol"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldNameEn holds the string denoting the name_en field in the database.
	FieldNameEn = "name_en"
	// FieldIsBase holds the string denoting the is_base field in the database.
	FieldIsBase = "is_base"
	// FieldConversionType holds the string denoting the conversion_type field in the database.
	FieldConversionType = "conversion_type"
	// FieldFactor holds the string denoting the factor field in the database.
	FieldFactor = "factor"
	// FieldOffset holds the string denoting the offset field in the database.
	FieldOffset = "offset"
	// FieldFormulaExpr holds the string denoting the formula_expr field in the database.
	FieldFormulaExpr = "formula_expr"
	// FieldPrecision holds the string denoting the precision field in the database.
	FieldPrecision = "precision"
	// FieldIsSiUnit holds the string denoting the is_si_unit field in the database.
	FieldIsSiUnit = "is_si_unit"
	// FieldIsLegalUnit holds the string denoting the is_legal_unit field in the database.
	FieldIsLegalUnit = "is_legal_unit"
	// FieldReferenceCount holds the string denoting the reference_count field in the database.
	FieldReferenceCount = "reference_count"
	// EdgeCategory holds the string denoting the category edge name in mutations.
	EdgeCategory = "category"
	// Table holds the table name of the unit in the database.
	Table = "thingmodel_units"
	// CategoryTable is the table that holds the category relation/edge.
	CategoryTable = "thingmodel_units"
	// CategoryInverseTable is the table name for the UnitCategory entity.
	// It exists in this package in order to avoid circular dependency with the "unitcategory" package.
	CategoryInverseTable = "thingmodel_unit_categories"
	// CategoryColumn is the table column denoting the category relation/edge.
	CategoryColumn = "category_id"
)

// Columns holds all SQL columns for unit fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldDeletedBy,
	FieldSortOrder,
	FieldIsEnabled,
	FieldTenantID,
	FieldCategoryID,
	FieldCode,
	FieldSymbol,
	FieldName,
	FieldNameEn,
	FieldIsBase,
	FieldConversionType,
	FieldFactor,
	FieldOffset,
	FieldFormulaExpr,
	FieldPrecision,
	FieldIsSiUnit,
	FieldIsLegalUnit,
	FieldReferenceCount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "go-wind-admin/app/admin/service/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder uint32
	// DefaultIsEnabled holds the default value on creation for the "is_enabled" field.
	DefaultIsEnabled bool
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// SymbolValidator is a validator for the "symbol" field. It is called by the builders before save.
	SymbolValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultIsBase holds the default value on creation for the "is_base" field.
	DefaultIsBase bool
	// DefaultFactor holds the default value on creation for the "factor" field.
	DefaultFactor float64
	// DefaultOffset holds the default value on creation for the "offset" field.
	DefaultOffset float64
	// DefaultPrecision holds the default value on creation for the "precision" field.
	DefaultPrecision int32
	// DefaultIsSiUnit holds the default value on creation for the "is_si_unit" field.
	DefaultIsSiUnit bool
	// DefaultIsLegalUnit holds the default value on creation for the "is_legal_unit" field.
	DefaultIsLegalUnit bool
	// DefaultReferenceCount holds the default value on creation for the "reference_count" field.
	DefaultReferenceCount uint32
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint32) error
)

// ConversionType defines the type for the "conversion_type" enum field.
type ConversionType string

// ConversionTypeLinear is the default value of the ConversionType enum.
const DefaultConversionType = ConversionTypeLinear

// ConversionType values.
const (
	ConversionTypeLinear      ConversionType = "LINEAR"
	ConversionTypeAffine      ConversionType = "AFFINE"
	ConversionTypeLogarithmic ConversionType = "LOGARITHMIC"
	ConversionTypeConditional ConversionType = "CONDITIONAL"
	ConversionTypeNone        ConversionType = "NONE"
)

func (ct ConversionType) String() string {
	return string(ct)
}

// ConversionTypeValidator is a validator for the "conversion_type" field enum values. It is called by the builders before save.
func ConversionTypeValidator(ct ConversionType) error {
	switch ct {
	case ConversionTypeLinear, ConversionTypeAffine, ConversionTypeLogarithmic, ConversionTypeConditional, ConversionTypeNone:
		return nil
	default:
		return fmt.Errorf("unit: invalid enum value for conversion_type field: %q", ct)
	}
}

// OrderOption defines the ordering options for the Unit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByIsEnabled orders the results by the is_enabled field.
func ByIsEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsEnabled, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByCategoryID orders the results by the category_id field.
func ByCategoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategoryID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// BySymbol orders the results by the symbol field.
func BySymbol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSymbol, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByNameEn orders the results by the name_en field.
func ByNameEn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameEn, opts...).ToFunc()
}

// ByIsBase orders the results by the is_base field.
func ByIsBase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsBase, opts...).ToFunc()
}

// ByConversionType orders the results by the conversion_type field.
func ByConversionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConversionType, opts...).ToFunc()
}

// ByFactor orders the results by the factor field.
func ByFactor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFactor, opts...).ToFunc()
}

// ByOffset orders the results by the offset field.
func ByOffset(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOffset, opts...).ToFunc()
}

// ByFormulaExpr orders the results by the formula_expr field.
func ByFormulaExpr(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFormulaExpr, opts...).ToFunc()
}

// ByPrecision orders the results by the precision field.
func ByPrecision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrecision, opts...).ToFunc()
}

// ByIsSiUnit orders the results by the is_si_unit field.
func ByIsSiUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsSiUnit, opts...).ToFunc()
}

// ByIsLegalUnit orders the results by the is_legal_unit field.
func ByIsLegalUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsLegalUnit, opts...).ToFunc()
}

// ByReferenceCount orders the results by the reference_count field.
func ByReferenceCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferenceCount, opts...).ToFunc()
}

// ByCategoryField orders the results by category field.
func ByCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCategoryStep(), sql.OrderByField(field, opts...))
	}
}
func newCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
	)
}
