// Code generated by ent, DO NOT EDIT.

package unit

import (
	"go-wind-admin/app/admin/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldDeletedBy, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldSortOrder, v))
}

// IsEnabled applies equality check predicate on the "is_enabled" field. It's identical to IsEnabledEQ.
func IsEnabled(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldIsEnabled, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldTenantID, v))
}

// CategoryID applies equality check predicate on the "category_id" field. It's identical to CategoryIDEQ.
func CategoryID(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldCategoryID, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldCode, v))
}

// Symbol applies equality check predicate on the "symbol" field. It's identical to SymbolEQ.
func Symbol(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldSymbol, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldName, v))
}

// NameEn applies equality check predicate on the "name_en" field. It's identical to NameEnEQ.
func NameEn(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldNameEn, v))
}

// IsBase applies equality check predicate on the "is_base" field. It's identical to IsBaseEQ.
func IsBase(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldIsBase, v))
}

// Factor applies equality check predicate on the "factor" field. It's identical to FactorEQ.
func Factor(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldFactor, v))
}

// Offset applies equality check predicate on the "offset" field. It's identical to OffsetEQ.
func Offset(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldOffset, v))
}

// FormulaExpr applies equality check predicate on the "formula_expr" field. It's identical to FormulaExprEQ.
func FormulaExpr(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldFormulaExpr, v))
}

// Precision applies equality check predicate on the "precision" field. It's identical to PrecisionEQ.
func Precision(v int32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldPrecision, v))
}

// IsSiUnit applies equality check predicate on the "is_si_unit" field. It's identical to IsSiUnitEQ.
func IsSiUnit(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldIsSiUnit, v))
}

// IsLegalUnit applies equality check predicate on the "is_legal_unit" field. It's identical to IsLegalUnitEQ.
func IsLegalUnit(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldIsLegalUnit, v))
}

// ReferenceCount applies equality check predicate on the "reference_count" field. It's identical to ReferenceCountEQ.
func ReferenceCount(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldReferenceCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldDeletedBy))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...uint32) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...uint32) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldSortOrder, v))
}

// SortOrderIsNil applies the IsNil predicate on the "sort_order" field.
func SortOrderIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldSortOrder))
}

// SortOrderNotNil applies the NotNil predicate on the "sort_order" field.
func SortOrderNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldSortOrder))
}

// IsEnabledEQ applies the EQ predicate on the "is_enabled" field.
func IsEnabledEQ(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldIsEnabled, v))
}

// IsEnabledNEQ applies the NEQ predicate on the "is_enabled" field.
func IsEnabledNEQ(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldIsEnabled, v))
}

// IsEnabledIsNil applies the IsNil predicate on the "is_enabled" field.
func IsEnabledIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldIsEnabled))
}

// IsEnabledNotNil applies the NotNil predicate on the "is_enabled" field.
func IsEnabledNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldIsEnabled))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldTenantID))
}

// CategoryIDEQ applies the EQ predicate on the "category_id" field.
func CategoryIDEQ(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldCategoryID, v))
}

// CategoryIDNEQ applies the NEQ predicate on the "category_id" field.
func CategoryIDNEQ(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldCategoryID, v))
}

// CategoryIDIn applies the In predicate on the "category_id" field.
func CategoryIDIn(vs ...uint32) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldCategoryID, vs...))
}

// CategoryIDNotIn applies the NotIn predicate on the "category_id" field.
func CategoryIDNotIn(vs ...uint32) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldCategoryID, vs...))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasSuffix(FieldCode, v))
}

// CodeIsNil applies the IsNil predicate on the "code" field.
func CodeIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldCode))
}

// CodeNotNil applies the NotNil predicate on the "code" field.
func CodeNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldCode))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContainsFold(FieldCode, v))
}

// SymbolEQ applies the EQ predicate on the "symbol" field.
func SymbolEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldSymbol, v))
}

// SymbolNEQ applies the NEQ predicate on the "symbol" field.
func SymbolNEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldSymbol, v))
}

// SymbolIn applies the In predicate on the "symbol" field.
func SymbolIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldSymbol, vs...))
}

// SymbolNotIn applies the NotIn predicate on the "symbol" field.
func SymbolNotIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldSymbol, vs...))
}

// SymbolGT applies the GT predicate on the "symbol" field.
func SymbolGT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldSymbol, v))
}

// SymbolGTE applies the GTE predicate on the "symbol" field.
func SymbolGTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldSymbol, v))
}

// SymbolLT applies the LT predicate on the "symbol" field.
func SymbolLT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldSymbol, v))
}

// SymbolLTE applies the LTE predicate on the "symbol" field.
func SymbolLTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldSymbol, v))
}

// SymbolContains applies the Contains predicate on the "symbol" field.
func SymbolContains(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContains(FieldSymbol, v))
}

// SymbolHasPrefix applies the HasPrefix predicate on the "symbol" field.
func SymbolHasPrefix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasPrefix(FieldSymbol, v))
}

// SymbolHasSuffix applies the HasSuffix predicate on the "symbol" field.
func SymbolHasSuffix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasSuffix(FieldSymbol, v))
}

// SymbolIsNil applies the IsNil predicate on the "symbol" field.
func SymbolIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldSymbol))
}

// SymbolNotNil applies the NotNil predicate on the "symbol" field.
func SymbolNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldSymbol))
}

// SymbolEqualFold applies the EqualFold predicate on the "symbol" field.
func SymbolEqualFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEqualFold(FieldSymbol, v))
}

// SymbolContainsFold applies the ContainsFold predicate on the "symbol" field.
func SymbolContainsFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContainsFold(FieldSymbol, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContainsFold(FieldName, v))
}

// NameEnEQ applies the EQ predicate on the "name_en" field.
func NameEnEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldNameEn, v))
}

// NameEnNEQ applies the NEQ predicate on the "name_en" field.
func NameEnNEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldNameEn, v))
}

// NameEnIn applies the In predicate on the "name_en" field.
func NameEnIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldNameEn, vs...))
}

// NameEnNotIn applies the NotIn predicate on the "name_en" field.
func NameEnNotIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldNameEn, vs...))
}

// NameEnGT applies the GT predicate on the "name_en" field.
func NameEnGT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldNameEn, v))
}

// NameEnGTE applies the GTE predicate on the "name_en" field.
func NameEnGTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldNameEn, v))
}

// NameEnLT applies the LT predicate on the "name_en" field.
func NameEnLT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldNameEn, v))
}

// NameEnLTE applies the LTE predicate on the "name_en" field.
func NameEnLTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldNameEn, v))
}

// NameEnContains applies the Contains predicate on the "name_en" field.
func NameEnContains(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContains(FieldNameEn, v))
}

// NameEnHasPrefix applies the HasPrefix predicate on the "name_en" field.
func NameEnHasPrefix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasPrefix(FieldNameEn, v))
}

// NameEnHasSuffix applies the HasSuffix predicate on the "name_en" field.
func NameEnHasSuffix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasSuffix(FieldNameEn, v))
}

// NameEnIsNil applies the IsNil predicate on the "name_en" field.
func NameEnIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldNameEn))
}

// NameEnNotNil applies the NotNil predicate on the "name_en" field.
func NameEnNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldNameEn))
}

// NameEnEqualFold applies the EqualFold predicate on the "name_en" field.
func NameEnEqualFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEqualFold(FieldNameEn, v))
}

// NameEnContainsFold applies the ContainsFold predicate on the "name_en" field.
func NameEnContainsFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContainsFold(FieldNameEn, v))
}

// IsBaseEQ applies the EQ predicate on the "is_base" field.
func IsBaseEQ(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldIsBase, v))
}

// IsBaseNEQ applies the NEQ predicate on the "is_base" field.
func IsBaseNEQ(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldIsBase, v))
}

// ConversionTypeEQ applies the EQ predicate on the "conversion_type" field.
func ConversionTypeEQ(v ConversionType) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldConversionType, v))
}

// ConversionTypeNEQ applies the NEQ predicate on the "conversion_type" field.
func ConversionTypeNEQ(v ConversionType) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldConversionType, v))
}

// ConversionTypeIn applies the In predicate on the "conversion_type" field.
func ConversionTypeIn(vs ...ConversionType) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldConversionType, vs...))
}

// ConversionTypeNotIn applies the NotIn predicate on the "conversion_type" field.
func ConversionTypeNotIn(vs ...ConversionType) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldConversionType, vs...))
}

// ConversionTypeIsNil applies the IsNil predicate on the "conversion_type" field.
func ConversionTypeIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldConversionType))
}

// ConversionTypeNotNil applies the NotNil predicate on the "conversion_type" field.
func ConversionTypeNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldConversionType))
}

// FactorEQ applies the EQ predicate on the "factor" field.
func FactorEQ(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldFactor, v))
}

// FactorNEQ applies the NEQ predicate on the "factor" field.
func FactorNEQ(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldFactor, v))
}

// FactorIn applies the In predicate on the "factor" field.
func FactorIn(vs ...float64) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldFactor, vs...))
}

// FactorNotIn applies the NotIn predicate on the "factor" field.
func FactorNotIn(vs ...float64) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldFactor, vs...))
}

// FactorGT applies the GT predicate on the "factor" field.
func FactorGT(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldFactor, v))
}

// FactorGTE applies the GTE predicate on the "factor" field.
func FactorGTE(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldFactor, v))
}

// FactorLT applies the LT predicate on the "factor" field.
func FactorLT(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldFactor, v))
}

// FactorLTE applies the LTE predicate on the "factor" field.
func FactorLTE(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldFactor, v))
}

// OffsetEQ applies the EQ predicate on the "offset" field.
func OffsetEQ(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldOffset, v))
}

// OffsetNEQ applies the NEQ predicate on the "offset" field.
func OffsetNEQ(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldOffset, v))
}

// OffsetIn applies the In predicate on the "offset" field.
func OffsetIn(vs ...float64) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldOffset, vs...))
}

// OffsetNotIn applies the NotIn predicate on the "offset" field.
func OffsetNotIn(vs ...float64) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldOffset, vs...))
}

// OffsetGT applies the GT predicate on the "offset" field.
func OffsetGT(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldOffset, v))
}

// OffsetGTE applies the GTE predicate on the "offset" field.
func OffsetGTE(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldOffset, v))
}

// OffsetLT applies the LT predicate on the "offset" field.
func OffsetLT(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldOffset, v))
}

// OffsetLTE applies the LTE predicate on the "offset" field.
func OffsetLTE(v float64) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldOffset, v))
}

// FormulaExprEQ applies the EQ predicate on the "formula_expr" field.
func FormulaExprEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldFormulaExpr, v))
}

// FormulaExprNEQ applies the NEQ predicate on the "formula_expr" field.
func FormulaExprNEQ(v string) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldFormulaExpr, v))
}

// FormulaExprIn applies the In predicate on the "formula_expr" field.
func FormulaExprIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldFormulaExpr, vs...))
}

// FormulaExprNotIn applies the NotIn predicate on the "formula_expr" field.
func FormulaExprNotIn(vs ...string) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldFormulaExpr, vs...))
}

// FormulaExprGT applies the GT predicate on the "formula_expr" field.
func FormulaExprGT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldFormulaExpr, v))
}

// FormulaExprGTE applies the GTE predicate on the "formula_expr" field.
func FormulaExprGTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldFormulaExpr, v))
}

// FormulaExprLT applies the LT predicate on the "formula_expr" field.
func FormulaExprLT(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldFormulaExpr, v))
}

// FormulaExprLTE applies the LTE predicate on the "formula_expr" field.
func FormulaExprLTE(v string) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldFormulaExpr, v))
}

// FormulaExprContains applies the Contains predicate on the "formula_expr" field.
func FormulaExprContains(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContains(FieldFormulaExpr, v))
}

// FormulaExprHasPrefix applies the HasPrefix predicate on the "formula_expr" field.
func FormulaExprHasPrefix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasPrefix(FieldFormulaExpr, v))
}

// FormulaExprHasSuffix applies the HasSuffix predicate on the "formula_expr" field.
func FormulaExprHasSuffix(v string) predicate.Unit {
	return predicate.Unit(sql.FieldHasSuffix(FieldFormulaExpr, v))
}

// FormulaExprIsNil applies the IsNil predicate on the "formula_expr" field.
func FormulaExprIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldFormulaExpr))
}

// FormulaExprNotNil applies the NotNil predicate on the "formula_expr" field.
func FormulaExprNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldFormulaExpr))
}

// FormulaExprEqualFold applies the EqualFold predicate on the "formula_expr" field.
func FormulaExprEqualFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldEqualFold(FieldFormulaExpr, v))
}

// FormulaExprContainsFold applies the ContainsFold predicate on the "formula_expr" field.
func FormulaExprContainsFold(v string) predicate.Unit {
	return predicate.Unit(sql.FieldContainsFold(FieldFormulaExpr, v))
}

// PrecisionEQ applies the EQ predicate on the "precision" field.
func PrecisionEQ(v int32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldPrecision, v))
}

// PrecisionNEQ applies the NEQ predicate on the "precision" field.
func PrecisionNEQ(v int32) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldPrecision, v))
}

// PrecisionIn applies the In predicate on the "precision" field.
func PrecisionIn(vs ...int32) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldPrecision, vs...))
}

// PrecisionNotIn applies the NotIn predicate on the "precision" field.
func PrecisionNotIn(vs ...int32) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldPrecision, vs...))
}

// PrecisionGT applies the GT predicate on the "precision" field.
func PrecisionGT(v int32) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldPrecision, v))
}

// PrecisionGTE applies the GTE predicate on the "precision" field.
func PrecisionGTE(v int32) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldPrecision, v))
}

// PrecisionLT applies the LT predicate on the "precision" field.
func PrecisionLT(v int32) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldPrecision, v))
}

// PrecisionLTE applies the LTE predicate on the "precision" field.
func PrecisionLTE(v int32) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldPrecision, v))
}

// PrecisionIsNil applies the IsNil predicate on the "precision" field.
func PrecisionIsNil() predicate.Unit {
	return predicate.Unit(sql.FieldIsNull(FieldPrecision))
}

// PrecisionNotNil applies the NotNil predicate on the "precision" field.
func PrecisionNotNil() predicate.Unit {
	return predicate.Unit(sql.FieldNotNull(FieldPrecision))
}

// IsSiUnitEQ applies the EQ predicate on the "is_si_unit" field.
func IsSiUnitEQ(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldIsSiUnit, v))
}

// IsSiUnitNEQ applies the NEQ predicate on the "is_si_unit" field.
func IsSiUnitNEQ(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldIsSiUnit, v))
}

// IsLegalUnitEQ applies the EQ predicate on the "is_legal_unit" field.
func IsLegalUnitEQ(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldIsLegalUnit, v))
}

// IsLegalUnitNEQ applies the NEQ predicate on the "is_legal_unit" field.
func IsLegalUnitNEQ(v bool) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldIsLegalUnit, v))
}

// ReferenceCountEQ applies the EQ predicate on the "reference_count" field.
func ReferenceCountEQ(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldEQ(FieldReferenceCount, v))
}

// ReferenceCountNEQ applies the NEQ predicate on the "reference_count" field.
func ReferenceCountNEQ(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldNEQ(FieldReferenceCount, v))
}

// ReferenceCountIn applies the In predicate on the "reference_count" field.
func ReferenceCountIn(vs ...uint32) predicate.Unit {
	return predicate.Unit(sql.FieldIn(FieldReferenceCount, vs...))
}

// ReferenceCountNotIn applies the NotIn predicate on the "reference_count" field.
func ReferenceCountNotIn(vs ...uint32) predicate.Unit {
	return predicate.Unit(sql.FieldNotIn(FieldReferenceCount, vs...))
}

// ReferenceCountGT applies the GT predicate on the "reference_count" field.
func ReferenceCountGT(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldGT(FieldReferenceCount, v))
}

// ReferenceCountGTE applies the GTE predicate on the "reference_count" field.
func ReferenceCountGTE(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldGTE(FieldReferenceCount, v))
}

// ReferenceCountLT applies the LT predicate on the "reference_count" field.
func ReferenceCountLT(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldLT(FieldReferenceCount, v))
}

// ReferenceCountLTE applies the LTE predicate on the "reference_count" field.
func ReferenceCountLTE(v uint32) predicate.Unit {
	return predicate.Unit(sql.FieldLTE(FieldReferenceCount, v))
}

// HasCategory applies the HasEdge predicate on the "category" edge.
func HasCategory() predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCategoryWith applies the HasEdge predicate on the "category" edge with a given conditions (other predicates).
func HasCategoryWith(preds ...predicate.UnitCategory) predicate.Unit {
	return predicate.Unit(func(s *sql.Selector) {
		step := newCategoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Unit) predicate.Unit {
	return predicate.Unit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Unit) predicate.Unit {
	return predicate.Unit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Unit) predicate.Unit {
	return predicate.Unit(sql.NotPredicates(p))
}
